### PR TITLE
Prep for 1.0.5 release

### PR DESCRIPTION
**Pull request by saifshaikh48**
This PR updates the operator version
to v1.0.5 for the next 4.6 release.

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
Thanks for working on this @saifshaikh48 
/lgtm

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Review by aravindhp — APPROVED** [review]
/approve

Thanks for doing this, @saifshaikh48

**Review by EricPonvelle — COMMENTED** [review]
/lgtm

Would a release note be necessary?

**Comment by mansikulkarni96** [comment]
@EricPonvelle don't think so, this release is only for updating the base image with the CVE fixes. It does not involve any feature changes or bug fixes.

**Comment by aravindhp** [comment]
/hold

Upgrade test is failing with `make: *** No rule to make target 'run-ci-e2e-upgrade-test'.  Stop.`

**Comment by aravindhp** [comment]
Remove hold and refresh once https://github.com/openshift/release/pull/18833 merges

**Pull request merged**
