### PR TITLE
WINC-1353: HPA support for Windows Containers

### PR DESCRIPTION
**Pull request by mansikulkarni96**
This PR adds support statement for HPA on Windows Containers. This feature has become available after recent monitoring development to get the pod resource metrics.  Tested this locally and it works for deployment scaling.
Needs to be verified by QE.

### CODE REVIEW

**Review by sebsoto — APPROVED** [review]

**Review by jrvaldes — APPROVED** [review]
/lgtm

Thanks @mansikulkarni96  for working on this.

**Comment by jrvaldes** [comment]
@mansikulkarni96   consider overriding the e2e jobs for this docs PR

**Comment by mansikulkarni96** [comment]
/override ci/prow/aws-e2e-operator ci/prow/azure-e2e-operator ci/prow/azure-e2e-upgrade ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-disconnected-e2e-operator 
ci/prow/vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator  ci/prow/wicd-unit-vsphere

**Comment by mansikulkarni96** [comment]
/override ci/prow/vsphere-e2e-operator  ci/prow/vsphere-proxy-e2e-operator ci/prow/wicd-unit-vsphere

**Pull request merged**
