### PR TITLE
Simplify installation manifest

### PR DESCRIPTION
**Pull request by jboxman**
I've updated this to match the configuration that's in the latest installation procedure for OCP

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/approve
/cc @codyhoag 
/cc @sgaoshang

**Comment by aravindhp** [comment]
@codyhoag please reflect this in the OpenShift WMCO docs if needed.
@sgaoshang please test the new manifest.
/cc @openshift/openshift-team-windows-containers

**Comment by codyhoag** [comment]
@jboxman did you plan to update this in [configuring-hybrid-ovnkubernetes.adoc](https://github.com/openshift/openshift-docs/blob/master/modules/configuring-hybrid-ovnkubernetes.adoc) also? Let me know; happy to do it, but don't want to replicate work. :slightly_smiling_face:

**Comment by sebsoto** [comment]
Was able to spin up a cluster and install WMCO with this
/lgtm

**Comment by sgaoshang** [comment]
QE smoke test passed, thanks.

**Pull request merged**
