### PR TITLE
WINC-547: [community-4.6][wmco] Don't log when a service is not found

### PR DESCRIPTION
**Pull request by aravindhp**
Use the command "sc.exe qe" and the error code "1060" as hints to not log the error. We are doing this as it was spamming the log with no informational benefit.

(cherry picked from commit e5b96f3991d81364748f884a820c2e70ab44f84f)

### CODE REVIEW

**Comment by aravindhp** [comment]
/hold

OKD cluster is consistently failing to come up

```
level=warning msg="Missing permissions to fetch Quotas and therefore will skip checking them: failed to load limits for servicequotas: failed to list default serviceqquotas for ec2: AccessDeniedException: User: arn:aws:iam::460538899914:user/origin-ci-robot-provision is not authorized to perform: servicequotas:ListAWSDefaultServiceQuotas, make sure you have `servicequotas:ListAWSDefaultServiceQuotas` persmission available to the user."
66
level=info msg="Creating infrastructure resources..."
67
level=info msg="Waiting up to 20m0s for the Kubernetes API at https://api.ci-op-mnbs5q02-e3e66.origin-ci-int-aws.dev.rhcloud.com:6443..."
68
level=error msg="Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get \"https://api.ci-op-mnbs5q02-e3e66.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators\": dial tcp 75.101.181.242:6443: connect: connection refused"
69
level=info msg="Pulling debug logs from the bootstrap machine"
70
level=info msg="Bootstrap gather logs captured here \"/tmp/installer/log-bundle-20201121121134.tar.gz\""
71
level=fatal msg="Bootstrap failed to complete: failed waiting for Kubernetes API: Get \"https://api.ci-op-mnbs5q02-e3e66.origin-ci-int-aws.dev.rhcloud.com:6443/version?timeout=32s\": dial tcp 54.147.155.168:6443: connect: connection refused"
72
2020/11/21 12:11:38 Failed to upload $KUBECONFIG: timed out waiting for the condition
73
error: failed to execute wrapped command: exit status 1
```

**Comment by LorbusChris** [comment]
We're hitting this here now again:
```
 time="2020-11-24T15:48:15Z" level=fatal msg="Failed to run operator: error waiting for CSV to install: timed out waiting for the condition"
operator-sdk run failed
deployment "windows-machine-config-operator" successfully rolled out 
```

I wonder whether https://github.com/openshift/windows-machine-config-operator/pull/191 might fix this?

**Comment by aravindhp** [comment]
#191 won't fix the rollout issue. We cannot follow the CI model for operators as discussed during the last standup. Following that model will prevent our tests from being referenced and run from other repos.

**Comment by aravindhp** [comment]
The workaround for the rollout issue is to either reproduce the problem locally, figure out what the problem is and fix the SDK if needed. Alternatively retry `run manifest` multiple times until it succeeds.

**Comment by LorbusChris** [comment]
OKD cluster came up :) 
/hold cancel

**Pull request merged**
