### PR TITLE
[release-4.10] WINC-1055: Prep for 5.1.2 release

### PR DESCRIPTION
**Pull request by jrvaldes**
This change bumps the patch version in prep for the next 5.1.2 release.

Ran `make bundle`

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by jrvaldes** [comment]
/hold

to investigate unrecognized command line option [error](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1716/pull-ci-openshift-windows-machine-config-operator-release-4.10-platform-none-vsphere-e2e-operator/1688575817669414912)

**Comment by mtnbikenc** [comment]
AWS jobs are being removed
/override ci/prow/aws-e2e-upgrade
/override ci/prow/aws-e2e-operator

**Pull request merged**
