### PR TITLE
[release-4.9] WINC-818: [test] Fix upgradeable condition test

### PR DESCRIPTION
**Pull request by saifshaikh48**
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1339

### CODE REVIEW

**Comment by saifshaikh48** [comment]
Might be running into https://github.com/kubernetes-sigs/controller-tools/issues/643
@mansikulkarni96 PTAL when you have time

**Review by aravindhp — APPROVED** [review]

**Comment by aravindhp** [comment]
/hold

```
 [1/2] STEP 47/47: RUN make build
go fmt ./...
go vet ./...
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported) 
```

**Comment by mtnbikenc** [comment]
@saifshaikh48 Please update this PR when you have a chance.

**Comment by saifshaikh48** [comment]
updated to import a go1.16 compatible version of the [client library](https://pkg.go.dev/github.com/operator-framework/operator-lifecycle-manager@v0.19.1/pkg/api/client/clientset/versioned)

**Comment by mtnbikenc** [comment]
Build issue resolved.
/hold cancel

**Pull request merged**
