### PR TITLE
WINC-1320: Use registry.k8s.io instead of old k8s.gcr.io

### PR DESCRIPTION
**Pull request by saifshaikh48**

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/test aws-e2e-operator
/test azure-e2e-operator
/test azure-e2e-upgrade
/test build
/test ci-bundle-wmco-bundle
/test gcp-e2e-operator
/test images
/test lint
/test nutanix-e2e-operator
/test platform-none-vsphere-e2e-operator
/test security
/test unit
/test vsphere-e2e-operator
/test vsphere-proxy-e2e-operator
/test wicd-unit-vsphere

run all but disconnected job, which needs https://github.com/openshift/release/pull/54788 to go in first

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by saifshaikh48** [comment]
/retest-required

a couple install failures and a couple strange flakes (query output clearly has an integer `0` or `1` but is being interpreted as empty string)

**Comment by saifshaikh48** [comment]
/vsphere-disconnected-e2e-operator

https://github.com/openshift/release/pull/54788 merged

**Comment by saifshaikh48** [comment]
/test vsphere-disconnected-e2e-operator

https://github.com/openshift/release/pull/54788 merged

**Comment by saifshaikh48** [comment]
/test azure-e2e-upgrade

operator image build flake

**Comment by jrvaldes** [comment]
@openshift/openshift-team-windows-containers   consider overriding `azure-e2e-upgrade` job  as it passed before

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_windows-machine-config-operator/2286/pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-upgrade/1821613252468019200

**Comment by saifshaikh48** [comment]
/cherry-pick release-4.17
/cherry-pick release-4.16
/cherry-pick release-4.15
/cherry-pick release-4.14

need to backport back to 4.14 before we can remove the old images from the test setup steps in release repo

**Comment by saifshaikh48** [comment]
/cherry-pick release-4.14

need to backport back to 4.14 before we can remove the old images from the test setup steps in release repo

**Pull request merged**
