### PR TITLE
[config] Update the k8s version in the CSV

### PR DESCRIPTION
**Pull request by jrvaldes**
Update the k8s version to v1.22 in the CSV

Follow-up to https://github.com/openshift/windows-machine-config-operator/pull/581/commits/6698f0296c05ca2e534c1f72265945c0ffbe98a0

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
Thanks for fixing this @jrvaldes 
PR can be reframed/retitled since the change is part of the config and not the bundle directly.

**Review by aravindhp — APPROVED** [review]
/approve

**Pull request merged**
