### PR TITLE
[release-4.13] [test] Capture stderr on oc adm node-logs failures 

### PR DESCRIPTION
**Pull request by alinaryan**
Manual cherry-pick of #1464 and #1531

### CODE REVIEW

**Review by aravindhp — CHANGES_REQUESTED** [review]
There's no reason to cherry-pick a bug and then fix it. Please introduce the correct version and then cherry-pick it other branches.

**Comment by sebsoto** [comment]
Seeing if the problem is reproduced here

**Comment by alinaryan** [comment]
/test aws-e2e-upgrade

timeout

`timed out waiting for daemonset noop-ds to scale, current status: {CurrentNumberScheduled:2 NumberMisscheduled:0 DesiredNumberScheduled:2 NumberReady:1 ObservedGeneration:1 UpdatedNumberScheduled:2 NumberAvailable:1 NumberUnavailable:1 CollisionCount:<nil> Conditions:[]}`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1533/pull-ci-openshift-windows-machine-config-operator-release-4.13-aws-e2e-upgrade/1641872977437921280

**Comment by alinaryan** [comment]
/test aws-e2e-upgrade

bootstrapping

`level=error msg=Bootstrap failed to complete: timed out waiting for the condition
level=error msg=Failed to wait for bootstrapping to complete. This error usually happens when there is a problem with control plane hosts that prevents the control plane operators from creating the control plane.`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1533/pull-ci-openshift-windows-machine-config-operator-release-4.13-aws-e2e-upgrade/1642979776480153600

**Pull request merged**
