### PR TITLE
[release-4.13] OCPBUGS-20259: Fix "WMCO does not wait for instance to reboot properly"

### PR DESCRIPTION
**Pull request by saifshaikh48**
- [[windows] Refactor instance reboot method](https://github.com/openshift/windows-machine-config-operator/commit/2ae380001073f93e9926613e6f96666c1dc32955) 
- [Add SSH off-line check to reboot logic](https://github.com/openshift/windows-machine-config-operator/commit/e70aa4b96902c902b21d25335e40c12ea9af6dd2)

manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1862

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@saifshaikh48 Can this be opened up for reviews?  release-4.13 branch is open

**Review by aravindhp — APPROVED** [review]

**Pull request merged**
