### PR TITLE
[release-4.13] submodule update 07/25

### PR DESCRIPTION
**Pull request by alinaryan**
[[submodule][ovn-kubernetes] Update to 256e112b4](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/babc154f4f251b1ed277e610d2b48ff6e3f76f04)
[[submodule][containernetworking-plugins] Update to 26001de](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/13615788490ee1daafb22376f2f55e6ca6ac0e1f)
[[submodule][promu] Update to 6c8c415](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/f5c4cf7f50d821761c88427f0c57fb7e26eb3033)
[[submodule][windows_exporter] Update to 3f5cfea](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/3dd581d312606a7aec12f83333212be6f73bce8a)
[[submodule][kubelet] Update to 73ac5612fbb](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/575cc188d237b58db99a0f46c0282b673a002014)
[[build] Update kubelet version to v1.26.6+73ac561](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/f0926dde5ff210677443687f2a00a2be9725b7e6)
[[submodule][kube-proxy] Update to ec42cea68da](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/87510b25cdc4b28fc92fe211a7687d641fd500c0)
[[build] Update kube-proxy version to v1.26.0+ec42cea](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/4b99dd30f2eefe5b963ab47ac20bcf438dc50598)
[[submodule][containerd] Update to bd15ee452](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/ea9d9a010b06d5e00a511e57560f2c01cff4762d)
[[build] Update containerd version to v1.6.21-5-gbd15ee452](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/a1edda6dbbd5dac97c67b6edebee00aff805602c)
[[submodule][cloud-provider-azure] Update to fb2d232da](https://github.com/openshift/windows-machine-config-operator/pull/1702/commits/0b9b6572c363ea52d0cd6373e2867f59769d89d9)

### CODE REVIEW

**Comment by aravindhp** [comment]
@alinaryan why are we holding submodule updates for backports?

**Comment by alinaryan** [comment]
@aravindhp I thought we were being strict with ordering, but I see it shouldn't matter for submodules. I'll remove the hold

**Review by aravindhp — APPROVED** [review]

**Comment by alinaryan** [comment]
/test vsphere-e2e-operator

Related to: https://redhat-internal.slack.com/archives/C015H2WDJRY/p1690378611448979

**Comment by alinaryan** [comment]
/test aws-e2e-upgrade

TestWMCO/destroy/Deletion timed out because daemonSet pods took too long to scale 

`timed out waiting for daemonset noop-ds to scale, current status: {CurrentNumberScheduled:2 NumberMisscheduled:0 DesiredNumberScheduled:2 NumberReady:1 ObservedGeneration:1 UpdatedNumberScheduled:2 NumberAvailable:1 NumberUnavailable:1 CollisionCount:<nil> Conditions:[]}`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1702/pull-ci-openshift-windows-machine-config-operator-release-4.13-aws-e2e-upgrade/1683888710841536512

**Comment by alinaryan** [comment]
/test aws-e2e-upgrade

TestWMCO/destroy/Deletion timed out because daemonSet pods took too long to scale

timed out waiting for daemonset noop-ds to scale, current status: {CurrentNumberScheduled:2 NumberMisscheduled:0 DesiredNumberScheduled:2 NumberReady:1 ObservedGeneration:1 UpdatedNumberScheduled:2 NumberAvailable:1 NumberUnavailable:1 CollisionCount:<nil> Conditions:[]}

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1702/pull-ci-openshift-windows-machine-config-operator-release-4.13-aws-e2e-upgrade/1684243389182119936

**Pull request closed without merging**
