### PR TITLE
WINC-1215: Upgrade OperatorSDK to 1.33.0

### PR DESCRIPTION
**Pull request by wgahnagl**
Updates the OperatorSDK to version 1.33.0

- migrates from go/v3 to go/v4 https://book.kubebuilder.io/migration/manually_migration_guide_gov3_to_gov4

### CODE REVIEW

**Review by sebsoto — CHANGES_REQUESTED** [review]
I don't see any changes related to https://book.kubebuilder.io/migration/manually_migration_guide_gov3_to_gov4#update-kustomize-manifests-with-the-changes-made-so-far, please ensure this is handled.

**Comment by wgahnagl** [comment]
> I don't see any changes related to https://book.kubebuilder.io/migration/manually_migration_guide_gov3_to_gov4#update-kustomize-manifests-with-the-changes-made-so-far, please ensure this is handled.

So the change that the update mentioned is that it's no longer using kustomizev2alpha, which we don't implement anywhere 
The changes it's recommending are to be sure that there's no scaffolding updates, but between v3 and v4 in the example, there doesn't seem to be any, and our structure is pretty much the same as the v4 example. I don't think these updates apply to us.

**Comment by mansikulkarni96** [comment]
https://book.kubebuilder.io/migration/manually_migration_guide_gov3_to_gov4 mentions following change to the layout:
`The controller(s) directory has been moved under a new directory called internal and renamed to singular as well controller`

**Comment by mansikulkarni96** [comment]
You can use https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v4 to compare the scaffolding structure between v3 and v4.

**Comment by saifshaikh48** [comment]
I think the kustomize v3 to v4 changes still need to be done -- there's Makefile, go.mod, and `config/` dir differences between [v3](https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v3) and [v4](https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v4)

**Pull request closed without merging**
