### PR TITLE
WINC-1163: Bump kube-proxy submodule to sdn-4.16-kubernetes-1.29.0

### PR DESCRIPTION
**Pull request by jrvaldes**
Ran:

```
./hack/update_submodules.sh -m kube-proxy -r sdn-4.16-kubernetes-1.29.0 master

```

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/lgtm

Thanks for including the command used to generate the commits ++@jrvaldes

**Comment by jrvaldes** [comment]
/test vsphere-proxy-e2e-operator

vm delete test failed, gathering more data points.

**Comment by jrvaldes** [comment]
/test vsphere-proxy-e2e-operator

ipi-install failed

**Comment by jrvaldes** [comment]
/test vsphere-proxy-e2e-operator

build timed out

**Comment by jrvaldes** [comment]
/hold 

should go after
- https://github.com/openshift/windows-machine-config-operator/pull/2000

**Comment by jrvaldes** [comment]
/hold cancel

rebase 1.29 PR merged

**Comment by jrvaldes** [comment]
/test aws-e2e-upgrade

to gather more data points.

**Pull request merged**
