### PR TITLE
[release-4.8][docs] DeploymentConfig limitation

### PR DESCRIPTION
**Pull request by mansikulkarni96**
(cherry picked from commit 53e82e4d36d7edc4b658685cd19ad8ee629692bb)

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/lgtm

**Comment by mansikulkarni96** [comment]
/retest
cluster setup issue with route 53 record.

**Comment by mansikulkarni96** [comment]
/retest
failed during de-provisioning step

**Pull request merged**
