### PR TITLE
[release-4.9] [csr_controller] RetryOnConflict in CSR approvals

### PR DESCRIPTION
**Pull request by mansikulkarni96**
Manual backport of #894 to fix vendoring.

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/lgtm

@selansen you have the `/approve` power :muscle:

**Comment by selansen** [comment]
> /lgtm
> 
> @selansen you have the `/approve` power muscle

I do. But if I am the first one to review the PR, I wanted to min 2 lgtm before I approve. The idea is if @sseago comes and review later he can approve. if I review late, I can review and approve it :)

**Pull request merged**
