### PR TITLE
Update powershell.ps1

### PR DESCRIPTION
**Pull request by christianh814**
Updated powershell script as it wasn't working "as-is" There was a problem with the ' (single quote). Probably some encoding issue.

### CODE REVIEW

**Review by ravisantoshgudimetla — APPROVED** [review]
Thank you for fixing this @christianh814 

/approve

**Review by aravindhp — APPROVED** [review]
Thanks for fixing this @christianh814 

/lgtm

**Comment by ravisantoshgudimetla** [comment]
Failing with error:

```
unable to read image registry.build02.ci.openshift.org/ci-op-by6q7tt1/stable@sha256:afa5603851ce1f5c4f63a3890694e7ed7802587f84cb85cc1a95d7942e07f177: unknown: unable to pull manifest from registry.svc.ci.openshift.org/ocp/4.8@sha256:afa5603851ce1f5c4f63a3890694e7ed7802587f84cb85cc1a95d7942e07f177: manifest unknown: manifest unknown
```

putting a hold for now. Feel free to remove it when addressed.

/hold

**Comment by sebsoto** [comment]
> Failing with error:
> 
> ```
> unable to read image registry.build02.ci.openshift.org/ci-op-by6q7tt1/stable@sha256:afa5603851ce1f5c4f63a3890694e7ed7802587f84cb85cc1a95d7942e07f177: unknown: unable to pull manifest from registry.svc.ci.openshift.org/ocp/4.8@sha256:afa5603851ce1f5c4f63a3890694e7ed7802587f84cb85cc1a95d7942e07f177: manifest unknown: manifest unknown
> ```
> 
> putting a hold for now. Feel free to remove it when addressed.
> 
> /hold

This is fixed now, removing hold

**Pull request merged**
