### PR TITLE
[docs]  bump vmtools image and auth keys for vSphere CI

### PR DESCRIPTION
**Pull request by jrvaldes**
- bump vmtools image to v1240
- update pub auth keys with openshift shared pub key

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

though not sure if we should explicitly put the openshift-dev pub key in authorized_keys or rather just leave a note in the vsphere internal docs that openshift-dev was used/should be used in packer builds

**Comment by sebsoto** [comment]
/override ci/prow/aws-e2e-operator ci/prow/aws-e2e-upgrade ci/prow/azure-e2e-operator ci/prow/azure-e2e-upgrade ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator ci/prow/wicd-unit-vsphere

**Comment by mtnbikenc** [comment]
Override for `ci/prow/vsphere-e2e-operator` was missed.

**Comment by jrvaldes** [comment]
@sebsoto  @mansikulkarni96   the overridden  jobs are running, PTAL. they may need another hit.

**Comment by sebsoto** [comment]
/override ci/prow/azure-e2e-upgrade ci/prow/platform-none-vsphere-e2e-operator

**Comment by sebsoto** [comment]
/override ci/prow/aws-e2e-operator ci/prow/aws-e2e-upgrade ci/prow/azure-e2e-operator ci/prow/azure-e2e-upgrade ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator ci/prow/wicd-unit-vsphere

**Comment by sebsoto** [comment]
/override ci/prow/vsphere-e2e-operator ci/prow/ci-bundle-wmco-bundle

**Pull request merged**
