### PR TITLE
[ci] Allow multiple VMs to be tested at once

### PR DESCRIPTION
**Pull request by sebsoto**
This commit refactors the WSU tests, allowing the test suite to test
against multiple VMs at the same time. This resulted in the concept of
tests against a VM and tests against the cluster to be implemented.

I've also added more context to certain test failures, by appending a
list of events related to the pod involved in the failure.

This commit also includes a workaround for
https://bugzilla.redhat.com/show_bug.cgi?id=1789881. This should be
removed once the bug is fixed.

### CODE REVIEW

**Comment by sebsoto** [comment]
There may be some flakes in the e2e-wsu test, however those are already present, and are caused by the OVN bug. After a few re-runs it should pass.

**Comment by sebsoto** [comment]
The content of this PR was pulled from https://github.com/openshift/windows-machine-config-operator/pull/123 as parts of that PR are blocked by the abovementioned bug

**Comment by aravindhp** [comment]
@sebsoto given you are pulling in code from #123, how about you also pull in  rest of the testing code, namely:

- getClusterVersion
- getLatestGithubRelease
- getReleaseArtifactURL
- getReleaseArtifactSHA

With the change of adding `getReleaseArtifactURL` and `getReleaseArtifactSHA` to the `framework` struct as exported functions. The call sites then won't need to have knowledge about `LatestRelease` and that can become an internal field in the struct. This will be a separate commit.

You can then re-title this PR as `[ci] Test framework` improvements.

**Comment by aravindhp** [comment]
> @sebsoto given you are pulling in code from #123, how about you also pull in rest of the testing code, namely:
> 
>     * getClusterVersion
> 
>     * getLatestGithubRelease
> 
>     * getReleaseArtifactURL
> 
>     * getReleaseArtifactSHA
> 
> 
> With the change of adding `getReleaseArtifactURL` and `getReleaseArtifactSHA` to the `framework` struct as exported functions. The call sites then won't need to have knowledge about `LatestRelease` and that can become an internal field in the struct. This will be a separate commit.
> 
> You can then re-title this PR as `[ci] Test framework` improvements.

Please ignore the above suggestion as @ravisantoshgudimetla prefers not introduce code which is not being used. I have added the above code in #139.

**Comment by ravisantoshgudimetla** [comment]
/hold

Seems networking is broken.

**Comment by aravindhp** [comment]
/hold

@sebsoto please ensure the PR passes `ci/prow/e2e-wsu` a few times and then we can merge.

**Comment by aravindhp** [comment]
@sebsoto please make the workaround a separate commit so that we can easily revert it.

**Comment by sebsoto** [comment]
Test passed so running job again

**Comment by sebsoto** [comment]
WSU tests passed 2/2 times. Running once more for good measure

**Comment by aravindhp** [comment]
@sebsoto looks like the `e2e-wsu` is still [failing](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/140/pull-ci-openshift-windows-machine-config-operator-master-e2e-wsu/605) with the workaround. So the workaround needs to be improved otherwise I don't a see a point in merging this.

**Comment by sebsoto** [comment]
Tests passed with new bug workaround, retrying
/test e2e-wsu

**Comment by sebsoto** [comment]
passed 2/2 times, running 3rd

**Comment by sebsoto** [comment]
3/3 passed running 4th
/test e2e-wsu

**Comment by sebsoto** [comment]
4/4 test runs passed. Going to rebase and have the final test run from that.

**Comment by sebsoto** [comment]
tests passed 5/5 times
retesting wni test due to flake
/test test-e2e-tools

**Comment by sebsoto** [comment]
/hold cancel
Removing hold as tests passed 5 times in a row

**Pull request merged**
