### PR TITLE
Bug 1896691: [k8s] Update submodule to current openshift:release-4.6

### PR DESCRIPTION
**Pull request by LorbusChris**
Updates the kubernetes submodule to https://github.com/openshift/kubernetes/commit/1348ff864868a6202addf58c3ee5e6ebf8fae77e

### CODE REVIEW

**Review by aravindhp — CHANGES_REQUESTED** [review]
Let's move to https://github.com/openshift/kubernetes/commit/b1ff88f8f9f1e49a4b4150833a3ce92a4eabdaa3

**Comment by LorbusChris** [comment]
Some more commits have merged into k8s, I've updated the submodule to https://github.com/openshift/kubernetes/commit/1348ff864868a6202addf58c3ee5e6ebf8fae77e

One thing to note is that the release-4.6 branch of openshift/kubernetes does not yet include the WinEvent change required to get docker logs from the Windows machines.

**Comment by LorbusChris** [comment]
We might want to wait until https://github.com/openshift/kubernetes/pull/446 makes it in

**Comment by sdodson** [comment]
/retitle Bug 1896691: [k8s] Update submodule to current openshift:release-4.6

**Comment by aravindhp** [comment]
Blocked waiting on https://github.com/openshift/kubernetes/pull/446

**Pull request merged**
