### PR TITLE
OCPBUGS-42827: [release-4.17] Adjust k8s version for kube 1.30

### PR DESCRIPTION
**Pull request by saifshaikh48**
Supports k8s versions 1.30 & 1.31.

### CODE REVIEW

**Comment by sebsoto** [comment]
/hold

needs its own bug

**Review by mansikulkarni96 — COMMENTED** [review]
/lgtm

**Review by jrvaldes — COMMENTED** [review]
/lgtm

**Comment by sebsoto** [comment]
/override ci/prow/azure-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-disconnected-e2e-operator ci/prow/vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator

**Pull request merged**
