### PR TITLE
[release-4.8] WINC-678: Upgrade to Operator SDK 1.15.0

### PR DESCRIPTION
**Pull request by alinaryan**
This PR updates Operator SDK in WMCO from v1.6.1 to latest v1.15.0.

Followed upgrade steps from https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.15.0/

Manual cherry pick of [#794](https://github.com/openshift/windows-machine-config-operator/pull/794)

### CODE REVIEW

**Comment by alinaryan** [comment]
\hold

**Comment by saifshaikh48** [comment]
/hold

code freeze until 3.1.1 ships

**Comment by alinaryan** [comment]
\test ci/prow/images

**Pull request merged**
