### PR TITLE
WINC-1339: Use kube 1.31

### PR DESCRIPTION
**Pull request by sebsoto**
Submodule changes generated with hack/update-submodules.sh

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
Should we also bump the kube-proxy version to use 1.31 tag with this?

**Comment by saifshaikh48** [comment]
/lgtm

I don’t think a 1.31 tag has been published yet in o/k but there is one is k/k. Anyway IMO we should move our submodule to track upstream k/k

**Review by mansikulkarni96 — APPROVED** [review]

**Comment by sebsoto** [comment]
/override ci/prow/azure-e2e-upgrade 

The minimum version needs to be bumped in 4.17 and here before this can pass. Overriding to unblock CI and will 'backport' the change

**Pull request merged**
