### PR TITLE
[community-4.8] [submodule] Update

### PR DESCRIPTION
**Pull request by sebsoto**
* [submodule][ovn-kubernetes] Update to https://github.com/openshift/ovn-kubernetes/commit/7da97fcfffb1770d980a85b5667b78d5c7f67c95
* [submodule][containernetworking-plugins] Update to https://github.com/openshift/containernetworking-plugins/commit/71a8b3469df865daf68cb893bfe313328d4be992
* [submodule][kubelet] Update to https://github.com/openshift/kubernetes/commit/38b3eccb7e23fd950b6c7b5ec1cc3075b630aac3

### CODE REVIEW

**Comment by aravindhp** [comment]
@sebsoto are the submodule commits the same as what is in `release-4.8`?

**Comment by sebsoto** [comment]
@aravindhp No, I can open a PR to update the release-4.8 submodules as well when it is caught up.

**Review by aravindhp — APPROVED** [review]
/approve

Lets get release-4.8 matched up once this goes in.

**Pull request merged**
