### PR TITLE
OCPBUGS-13244: Install container feature silently

### PR DESCRIPTION
**Pull request by aravindhp**
- [windows] Install container feature silently 
- [test] Use 2019-datacenter-smalldisk for Azure

Fixes OCPBUGS-13244

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by aravindhp** [comment]
/test aws-e2e-operator

Cluster [failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1626/pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-operator/1661764404842074112) to come up due to [OCPBUGS-678](https://issues.redhat.com/browse/OCPBUGS-678)

**Comment by aravindhp** [comment]
/retest-required

On mobile and didn’t check failures

**Comment by aravindhp** [comment]
/retest-required

DaemonSet scaling flake

**Pull request merged**
