### PR TITLE
[release-4.13] Reuse testContext within each test suite

### PR DESCRIPTION
**Pull request by sebsoto**
Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1621. Manual cherry-pick was required as nutanix support was not backported into release-4.13

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]

**Comment by aravindhp** [comment]
/retest-required

All vSphere based jobs are failing with image pull backoffs:
```
* 2023-06-26T21:15:13Z 487x kubelet: Back-off pulling image "image-registry.openshift-image-registry.svc:5000/ci-op-287f8mll/pipeline@sha256:ec16f510e8cd1cceeddc6888fcb37c6d6b7c6863fbc70bdbe660a8ccad4bab6a"
* 2023-06-26T19:25:29Z 3x kubelet: Error: ImagePullBackOff  ```

**Comment by alinaryan** [comment]
LGTM

**Comment by sebsoto** [comment]
possible solution to vsphere issue has been implemented in CI

**Comment by sebsoto** [comment]
/retest-required

Daemonset flake on aws.

**Pull request merged**
