### PR TITLE
[release-4.13] OCPBUGS-23016: Introduce upgrading label to block concurrent upgrades

### PR DESCRIPTION
**Pull request by jrvaldes**
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1901

### CODE REVIEW

**Comment by jrvaldes** [comment]
azure-e2e-upgrade [failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1931/pull-ci-openshift-windows-machine-config-operator-release-4.13-azure-e2e-upgrade/1721925720613064704) with timeout while waiting for Windows nodes to come up as shown in [WMCO logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1931/pull-ci-openshift-windows-machine-config-operator-release-4.13-azure-e2e-upgrade/1721925720613064704/artifacts/azure-e2e-upgrade/gather-extra/artifacts/pods/openshift-windows-machine-config-operator_windows-machine-config-operator-fbcc67dbd-bjbhd_manager.log) 
```
2023-11-07T18:51:19Z	INFO	controller.windowsmachine	node upgrade has been blocked, as it can not be ensured that workloads will not be disrupted. If an in-tree persistent storage volume is in use, please ensure the CSI drivers for the given node have been deployed. This block must be overriden by applying the label windowsmachineconfig.openshift.io/allow-upgrade=true to the node. It is recommended to unblock Nodes individually, and to wait for the upgrade to complete sucessfully before unblocking another Node.
2023-11-07T18:51:19Z	DEBUG	events	node upgrade has been blocked, as it can not be ensured that workloads will not be disrupted. If an in-tree persistent storage volume is in use, please ensure the CSI drivers for the given node have been deployed. This block must be overriden by applying the label windowsmachineconfig.openshift.io/allow-upgrade=true to the node. It is recommended to unblock Nodes individually, and to wait for the upgrade to complete sucessfully before unblocking another Node.	{"type": "Warning", "object": {"kind":"Node","name":"e2e-wm-jtz7v","uid":"eeec953c-189a-4ad3-b38e-74671b509657","apiVersion":"v1","resourceVersion":"51048"}, "reason": "UpgradeBlocked"}
```

**Comment by mtnbikenc** [comment]
/hold
Until after 7.2.0

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Pull request merged**
