### PR TITLE
WINC-667: [release-4.8] [vendor] Bump OpensShift dependencies to latest

### PR DESCRIPTION
**Pull request by mansikulkarni96**
This PR bumps OpenShift depedencies to latest
release-4.8 commits.
Bumped github.com/openshift/api, github.com/openshift/library-go
and github.com/openshift/machine-api-operator.
Ran `go mod tidy && go mod vendor && go mod verify`
This commit also fixes `make build` by changing
azureprovider.ManagedDisk -> azureprovider.ManagedDiskParameters
in test/e2e/providers/azure/azure.go

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
Thanks for doing this, @mansikulkarni96

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Pull request merged**
