### PR TITLE
WINC-548: Update submodules to release-4.7 branches

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
Thanks for doing this, @LorbusChris 

/approve

**Comment by aravindhp** [comment]
/hold

Still seeing the same `hybrid-overlay` issue. We need to bump to https://github.com/openshift/ovn-kubernetes/commit/1ff61e4a62ade22c6fd19ab2a411ccd70e4d3b05

**Comment by LorbusChris** [comment]
updated to current tips of 4.7 branches
/hold cancel

**Pull request merged**
