### PR TITLE
[release-4.17] submodule update 08 12

### PR DESCRIPTION
**Pull request by wgahnagl**
[[submodule][ovn-kubernetes] Update to 190304949](https://github.com/openshift/windows-machine-config-operator/commit/d0309816d631a4c12ed8829c8d78a7da0e4fdb50)
[[submodule][kubelet] Update to 43740e9179f](https://github.com/openshift/windows-machine-config-operator/commit/c4d6b845cb559089ef85f77ce41098060a82f5a7)
[[build] Update kubelet version to v1.30.3+43740e9](https://github.com/openshift/windows-machine-config-operator/commit/a2d5c4cba6025fd2076763127c01628f885cd614)
[[vendor] Use v1.30.3+43740e9 k8s and OpenShift libraries](https://github.com/openshift/windows-machine-config-operator/commit/7a0138f1102cfd8ccab0a7037bfb9f07ccc53a94)

### CODE REVIEW

**Review by mansikulkarni96 — APPROVED** [review]

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by jrvaldes** [comment]
/close 

in favor of
- https://github.com/openshift/windows-machine-config-operator/pull/2390

**Pull request closed without merging**
