### PR TITLE
[release-4-17] Use updated konflux images

### PR DESCRIPTION
**Pull request by sebsoto**

### CODE REVIEW

**Comment by jrvaldes** [comment]
/title [release-4-17] [build] Use updated konflux images

**Comment by sebsoto** [comment]
/override ci/prow/ci-bundle-wmco-bundle ci/prow/images "Red Hat Konflux / Red Hat Konflux / windows-machine-config-operator-staging-release-4-17-ec / windows-machine-config-operator-release-4-17"

**Comment by sebsoto** [comment]
/override ci/prow/ci-bundle-wmco-bundle ci/prow/images "Red Hat Konflux / windows-machine-config-operator-staging-release-4-17-ec / windows-machine-config-operator-release-4-17"

**Pull request merged**
