### PR TITLE
[release-4.16] Submodule update 07/03

### PR DESCRIPTION
**Pull request by sebsoto**

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by mansikulkarni96** [comment]
/test vsphere-proxy-e2e-operator
cluster install failure

**Comment by sebsoto** [comment]
/override ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-e2e-operator
Passed before, failing due to CI issues.

**Pull request merged**
