### PR TITLE
[release-4.10] WINC-818: [test] Fix upgradeable condition test

### PR DESCRIPTION
**Pull request by saifshaikh48**
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1318
Updated vendor commit for conflicts.

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
Thanks for opening this @saifshaikh48 
/lgtm

**Comment by saifshaikh48** [comment]
/cherry-pick release-4.9

The 4.9 cherry-pick needs https://github.com/openshift/windows-machine-config-operator/pull/1340 to merge first (missing backport causing merge conflicts).

**Review by sebsoto — APPROVED** [review]

**Pull request merged**
