### PR TITLE
WINC-559: Bump to Kubernetes 1.20.0

### PR DESCRIPTION
**Pull request by sebsoto**
This PR  bumps all Kubernetes libraries being imported to Kubernetes 1.20.0.

### CODE REVIEW

**Review by aravindhp — COMMENTED** [review]
@sebsoto are you planning on bumping the client libraries too? I suggest you do that in this same PR.

**Comment by sebsoto** [comment]
@aravindhp That was done in https://github.com/openshift/windows-machine-config-operator/pull/230/commits/aa4a8607e657e90c9a97ef46b4fccad87328ef4c

**Comment by VaishnaviHire** [comment]
LGTM, except update submodule commit message needs to follow [this](https://github.com/openshift/windows-machine-config-operator/commit/021f06fee4d77159797b71d617137a59c09ff7ec) pattern

**Review by aravindhp — CHANGES_REQUESTED** [review]
Mostly lgtm except for following the [pattern](https://github.com/openshift/windows-machine-config-operator/commit/021f06fee4d77159797b71d617137a59c09ff7ec) for the submodule update as @VaishnaviHire called out.

**Review by aravindhp — APPROVED** [review]
/approve

**Comment by aravindhp** [comment]
/hold

@sebsoto please look into why the clusters are not coming up

**Comment by LorbusChris** [comment]
Blocked on: https://github.com/openshift/installer/pull/4490

**Comment by aravindhp** [comment]
Revert PR, https://github.com/openshift/kubernetes/pull/496, should unblock this PR.

**Comment by aravindhp** [comment]
Now waiting on https://github.com/openshift/kubernetes/pull/498

**Comment by aravindhp** [comment]
Now waiting on https://github.com/openshift/kubernetes/pull/500

**Pull request merged**
