### PR TITLE
[release-4.17] Enable hermetic builds for konflux

### PR DESCRIPTION
**Pull request by sebsoto**
Set konflux builds to run without network connection. Required for compliance reasons.

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by sebsoto** [comment]
/override " Red Hat Konflux / Red Hat Konflux / windows-machine-config-operator-staging-release-4-17-ec / windows-machine-config-operator-release-4-17 "

**Comment by sebsoto** [comment]
/override " Red Hat Konflux / Red Hat Konflux / windows-machine-config-operator-staging-release-4-17-ec / windows-machine-config-operator-release-4-17"

**Comment by sebsoto** [comment]
/override "Red Hat Konflux / windows-machine-config-operator-staging-release-4-17-ec / windows-machine-config-operator-release-4-17"

**Pull request merged**
