### PR TITLE
Bug 2067890: Update prometheus-operator/pkg/client

### PR DESCRIPTION
**Pull request by aravindhp**
Ran:
```
go get -u github.com/prometheus-operator/prometheus-operator/pkg/client
go mod tidy
go mod vendor
go mod verify
```
Fixes BZ#2067890

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by aravindhp** [comment]
I am investigating:
```
 deployment "windows-machine-config-operator" successfully rolled out
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:96:31: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:177:35: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:428:37: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:937:48: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:1143:45: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:1160:42: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:1195:52: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/decode.go:1261:42: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:158:16: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:175:22: undefined: any
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:175:22: too many errors
note: module requires Go 1.18
FAIL	github.com/openshift/windows-machine-config-operator/test/e2e [build failed] 
```
And I see the following in the [WMCO logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1231/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator/1567279912518160384/artifacts/vsphere-e2e-operator/gather-extra/artifacts/pods/openshift-windows-machine-config-operator_windows-machine-config-operator-857b574b44-7b9pz_manager.log):
```
2022-09-07T00:46:41Z	ERROR	Reconciler error	{"controller": "configmap", "controllerGroup": "", "controllerKind": "ConfigMap", "configMap": {"name":"windows-services-6.0.0-5c7656d-dirty","namespace":"openshift-windows-machine-config-operator"}, "namespace": "openshift-windows-machine-config-operator", "name": "windows-services-6.0.0-5c7656d-dirty", "reconcileID": "a57cc698-67cd-4f60-9a35-424dabe33b9e", "error": "unable to create signer from private key secret: Secret \"cloud-private-key\" not found", "errorVerbose": "Secret \"cloud-private-key\" not found\nunable to create signer from private key secret\ngithub.com/openshift/windows-machine-config-operator/controllers.(*ConfigMapReconciler).Reconcile\n\t/build/windows-machine-config-operator/controllers/configmap_controller.go:134\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/build/windows-machine-config-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234
```
which implies the `cloud-private-key` never got created. This is very puzzling. I am not able to reproduce on my dev vSphere cluster.

**Comment by aravindhp** [comment]
Blocked by https://github.com/openshift/release/pull/31573

**Comment by aravindhp** [comment]
https://github.com/openshift/release/pull/31573 was superseded by https://github.com/openshift/release/pull/32173 but that did not fix the WMCO repo. I have opened https://github.com/openshift/release/pull/32176

**Comment by aravindhp** [comment]
Blocked by #1247

**Review by sebsoto — APPROVED** [review]

**Comment by aravindhp** [comment]
/retest-required

`aws-e2e-upgrade`  went past the 4 hr window for tests to complete

**Comment by aravindhp** [comment]
Seeing the following failure:
```
 === RUN   TestWMCO/create/Services_ConfigMap_validation/Invalid_services_ConfigMap_deletion
    validation_test.go:517: 
        	Error Trace:	validation_test.go:517
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestWMCO/create/Services_ConfigMap_validation/Invalid_services_ConfigMap_deletion
        	Messages:   	error testing handling of invalid ConfigMap 
```
The log also has throttling warning:
```
I0913 22:11:14.791018   11634 request.go:601] Waited for 1.650274931s due to client-side throttling, not priority and fairness, request: GET:https://api.ci-op-qw7c4x3w-4bc28.origin-ci-int-aws.dev.rhcloud.com:6443/apis/autoscaling.openshift.io/v1beta1?timeout=32s
```
It is possible that's the reason for the time out.

/retest-required

**Comment by mansikulkarni96** [comment]
Thanks for fixing this @aravindhp 
/lgtm

**Comment by alinaryan** [comment]
thanks Aravindh!
/lgtm

**Comment by aravindhp** [comment]
/test vsphere-e2e-operator

Opened WINC-887 to track vsphere-e2e failing with `unable to change default shell of machine`

**Comment by aravindhp** [comment]
/override ci/prow/azure-e2e-operator 

The bug is agnostic to a provider

**Comment by aravindhp** [comment]
/test vsphere-e2e-operator

Not sure what the [failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1231/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator/1570129393261481984) actually is

```
 Writing manifest to image destination
Storing signatures
time="2022-09-14T19:35:10Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
I0914 19:35:10.452629       1 defaults.go:102] Defaulting to storage driver "overlay" with options [mountopt=metacopy=on].
Caching blobs under "/var/cache/blobs".
Pulling image image-registry.openshift-image-registry.svc:5000/ci-op-qr2immij/pipeline@sha256:f65d3a5dbcfdc5794b7f79b2bda6807f4031f3d978d2bf4fbc89f7ba673c23e9 ...
Trying to pull image-registry.openshift-image-registry.svc:5000/ci-op-qr2immij/pipeline@sha256:f65d3a5dbcfdc5794b7f79b2bda6807f4031f3d978d2bf4fbc89f7ba673c23e9...
Getting image source signatures
Copying blob sha256:028c90921d85568d97ca341b5433f597252a949b5c8189469e7da168e22c2a04
Copying blob sha256:2d473b07cdd5f0912cd6f1a703352c82b512407db6b05b43f2553732b55df3bc
Copying config sha256:d300066e042ebb9261f719e85e81aca869ed8296d974df3898a0e5b468b6c88e
Writing manifest to image destination
Storing signatures
Adding transient rw bind mount for /run/secrets/rhsm
[1/2] STEP 1/58: FROM image-registry.openshift-image-registry.svc:5000/ci-op-qr2immij/pipeline@sha256:f65d3a5dbcfdc5794b7f79b2bda6807f4031f3d978d2bf4fbc89f7ba673c23e9 AS build
Trying to pull image-registry.openshift-image-registry.svc:5000/ci-op-qr2immij/pipeline@sha256:f65d3a5dbcfdc5794b7f79b2bda6807f4031f3d978d2bf4fbc89f7ba673c23e9...
INFO[2022-09-14T19:35:24Z] Ran for 14m13s                               
ERRO[2022-09-14T19:35:24Z] Some steps failed:                           
ERRO[2022-09-14T19:35:24Z] 
  * could not run steps: step windows-machine-config-operator-test failed: the build windows-machine-config-operator-test failed after 2m50s with reason DockerBuildFailed: Dockerfile build strategy has failed. 
INFO[2022-09-14T19:35:24Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:building_project_image' 
```

**Comment by aravindhp** [comment]
> @aravindhp: #1231 failed to apply on top of branch "release-4.11":

Waiting on #1255 before opening manual backport

**Pull request merged**
