### PR TITLE
Submodule update 07/10

### PR DESCRIPTION
**Pull request by sebsoto**
* https://github.com/openshift/ovn-kubernetes/commit/e236fea83d62de8b60b9456770a3e0b525830051
* https://github.com/openshift/kubernetes/commit/af29f64acbf9e6d33cde7f3194cf858f54058d3b
* https://github.com/openshift/cloud-provider-azure/commit/ce1b81a02fd012f3edbd54642284555b89c7e852

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]

**Comment by aravindhp** [comment]
/retest-required

Upgrade test timed out

**Comment by saifshaikh48** [comment]
/retest-required

daemonset flake on deletion test
```
timed out waiting for daemonset noop-ds to scale, current status: {CurrentNumberScheduled:2 NumberMisscheduled:0 DesiredNumberScheduled:2 NumberReady:1 ObservedGeneration:1 UpdatedNumberScheduled:2 NumberAvailable:1 NumberUnavailable:1 CollisionCount:<nil> Conditions:[]}
```

**Comment by aravindhp** [comment]
/hold

For #1649 to merge first.

**Comment by aravindhp** [comment]
/retest-required

[GCP](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1682/pull-ci-openshift-windows-machine-config-operator-master-gcp-e2e-operator/1679483707120947200) looks like an install flae:
```
I0713 14:44:06.458729     123 request.go:696] Waited for 1.000129777s due to client-side throttling, not priority and fairness, request: GET:https://api.ci-op-44818nlm-8411c.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:6443/apis/config.openshift.io/v1/clusteroperators?fieldSelector=metadata.name%3Doperator-lifecycle-manager&limit=500&resourceVersion=0
level=error msg=Cluster operator etcd does not meet stability threshold of Progressing=false for greater than 30 seconds with Reason: "NodeInstaller" and Message: "NodeInstallerProgressing: 1 nodes are at revision 7; 2 nodes are at revision 8"
Installer exit with code 7
```

[vSphere](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1682/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator/1679483709419425792) test is failing because the deployment to test storage is not coming up but given it passed in the past, I am retesting:

**Comment by aravindhp** [comment]
/retest-required 

WinC watcher please follow through and get this merged

**Pull request merged**
