### PR TITLE
[release-4.9] WINC-678: Upgrade to Operator SDK 1.15.0

### PR DESCRIPTION
**Pull request by alinaryan**
This PR updates Operator SDK in WMCO from v1.6.1 to latest v1.15.0.

Followed upgrade steps from https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.15.0/

Manual cherry pick of [#794](https://github.com/openshift/windows-machine-config-operator/pull/794)

### CODE REVIEW

**Comment by alinaryan** [comment]
\hold

**Comment by saifshaikh48** [comment]
I don't see the equivalent of commit https://github.com/openshift/windows-machine-config-operator/pull/794/commits/51a5ead764f0e4149656aaffb95ecc5373ce9429 in this PR. Comment applies to  https://github.com/openshift/windows-machine-config-operator/pull/840 and https://github.com/openshift/windows-machine-config-operator/pull/839 as well.

**Comment by saifshaikh48** [comment]
/hold

code freeze until 4.0.1 ships

**Comment by alinaryan** [comment]
/test aws-e2e-upgrade
Flake retest. Saw same failure on two previous PRs.

**Comment by alinaryan** [comment]
/test vsphere-e2e-operator
Retest required due to vcenter crashing during last test.

**Pull request merged**
