### PR TITLE
[release-4.8] [windows] Increase kubelet verbosity in debug

### PR DESCRIPTION
**Pull request by jrvaldes**
This is manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1303

### CODE REVIEW

**Comment by jrvaldes** [comment]
/hold 

Depends on:
- https://github.com/openshift/windows-machine-config-operator/pull/1295

**Comment by aravindhp** [comment]
@jrvaldes you should rather cherry pick from the release-4.9 PR

**Comment by mtnbikenc** [comment]
@jrvaldes Please address this [comment](https://github.com/openshift/windows-machine-config-operator/pull/1304#issuecomment-1301330059).

**Comment by jrvaldes** [comment]
> @jrvaldes Please address this [comment](https://github.com/openshift/windows-machine-config-operator/pull/1304#issuecomment-1301330059).

This comment was addressed on [Nov 3, 2022](https://github.com/openshift/windows-machine-config-operator/pull/1304#event-7737134552)

**Comment by aravindhp** [comment]
@jrvaldes How have you addressed this [comment](https://github.com/openshift/windows-machine-config-operator/pull/1304#issuecomment-1301330059)? You need to close this PR and the cherry pick from the release-4.9 PR.

**Comment by jrvaldes** [comment]
> @jrvaldes How have you addressed this [comment](https://github.com/openshift/windows-machine-config-operator/pull/1304#issuecomment-1301330059)? You need to close this PR and the cherry pick from the release-4.9 PR.

I had manually cherry-picked the commit from release-4.9 PR. I see your point and will adjust accordingly.

**Comment by jrvaldes** [comment]
Closing this PR to leverage the automated cherry-pick:
- https://github.com/openshift/windows-machine-config-operator/pull/1329

**Pull request closed without merging**
