### PR TITLE
[release-4.13] WINC-1025: Enable CSI plugins on Windows nodes

### PR DESCRIPTION
**Pull request by jrvaldes**
Manual backport of https://github.com/openshift/windows-machine-config-operator/pull/1530

### CODE REVIEW

**Comment by jrvaldes** [comment]
/hold

Needs backport of https://github.com/openshift/windows-machine-config-operator/pull/1719 to fix the issue with AWS AMI affecting aws-e2e-upgrade job.

**Review by sebsoto — APPROVED** [review]

**Comment by jrvaldes** [comment]
> /hold
> 
> Needs backport of #1719 to fix the issue with AWS AMI affecting aws-e2e-upgrade job.

Blocked by:
- https://github.com/openshift/windows-machine-config-operator/pull/1722

**Pull request merged**
