### PR TITLE
[release-4.6] Backports from master 20201117

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
commit 'ensure all files have correct hash' will have to be edited to remove changes involving windows_exporter.

**Review by aravindhp — CHANGES_REQUESTED** [review]
This seems like a subset of commits from master. This fine grained level of cherry-picking will give rise to more difficult merges in the future. Like I mentioned before, it will be easier to back port all changes minus new features to the `release-4.6` branch.

**Comment by LorbusChris** [comment]
@aravindhp this includes all changes that have not yet been backported minus the windows_exporter changes (a number of changes has already been backported). I'll fix the issue mentioned by @mansikulkarni96

**Comment by aravindhp** [comment]
@LorbusChris this definitely is not pulling all the required changes. Please see this [diff](https://github.com/openshift/windows-machine-config-operator/compare/release-4.6...master ).

**Comment by LorbusChris** [comment]
@aravindhp the GH view isn't great for this. This is the diff generated with `git diff master backports-4.6`:
[backports.diff.txt](https://github.com/openshift/windows-machine-config-operator/files/5555679/backports.diff.txt)

**Comment by LorbusChris** [comment]
What I did was:
```
git checkout release-4.6
git checkout -b backports-4.6
git merge master
git rebase -i HEAD~1
<drop monitoring commits>
<fixup conflicts>
```

**Comment by aravindhp** [comment]
@LorbusChris not sure what you are doing wrong. Bottom line, PRs like #148, #167 (to name a couple) are not getting pulled in.

**Comment by aravindhp** [comment]
@LorbusChris your fork's master is not in sync with upstream. You should see a merge conflict with master.

**Comment by LorbusChris** [comment]
@aravindhp yes it is up to date :) please take a look at the commits that have already been backported in https://github.com/openshift/windows-machine-config-operator/pull/170, like #148:

https://github.com/openshift/windows-machine-config-operator/commits/release-4.6

#167 is included in this PR.

**Comment by aravindhp** [comment]
/approve

Sorry @LorbusChris. I must be doing something wrong locally.

**Review by aravindhp — APPROVED** [review]

**Pull request merged**
