### PR TITLE
[build] Update Dockerfiles to use rhel-9, openshift-4.13 base image

### PR DESCRIPTION
**Pull request by mansikulkarni96**
[build] Update Dockerfiles to use rhel-9-release-golang-1.19-openshift-4.13 base image

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/lgtm

Any changes needed gitlab/distgit?

**Review by sebsoto — APPROVED** [review]

**Comment by mansikulkarni96** [comment]
/retest-required
Azure cluster failed to come up.

**Comment by mansikulkarni96** [comment]
/retest-required
`level=error msg=APIServicesAvailable: apiservices.apiregistration.k8s.io/v1.template.openshift.io: not available: failing or missing response from https://10.128.0.40:8443/apis/template.openshift.io/v1: Get "https://10.128.0.40:8443/apis/template.openshift.io/v1": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
level=error msg=Cluster operator operator-lifecycle-manager-packageserver Available is False with ClusterServiceVersionNotSucceeded: ClusterServiceVersion openshift-operator-lifecycle-manager/packageserver observed in phase Failed with reason: InstallCheckFailed, message: install timeout`

**Pull request merged**
