### PR TITLE
Release 4.15 submodule update 10 07

### PR DESCRIPTION
**Pull request by saifshaikh48**

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/hold

vsphere tests blocked til the backport https://github.com/openshift/windows-machine-config-operator/pull/2461 merges

**Comment by saifshaikh48** [comment]
will be able to remove the hold here once https://github.com/openshift/windows-machine-config-operator/pull/2474 merges

**Comment by jrvaldes** [comment]
> will be able to remove the hold here once #2474 merges

Outdated submodule PR, a fresh one should be opened.

**Comment by saifshaikh48** [comment]
/test vsphere-e2e-operator
/test azure-e2e-operator

vsphere test timed out during deprovision :/
https://github.com/openshift/windows-machine-config-operator/pull/2474 merged to unblock azure

**Comment by mansikulkarni96** [comment]
/override ci/prow/aws-e2e-operator ci/prow/azure-e2e-operator ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator ci/prow/wicd-unit-vsphere ci/prow/azure-e2e-upgrade

**Comment by mansikulkarni96** [comment]
/override ci/prow/azure-e2e-upgrade ci/prow/ci-bundle-wmco-bundle ci/prow/images

**Pull request merged**
