### PR TITLE
Submodule update 07/18

### PR DESCRIPTION
**Pull request by wgahnagl**
https://github.com/openshift/ovn-kubernetes/commit/567aee061b529bef8671e0423fda2242fdc6f568
https://github.com/openshift/containernetworking-plugins/commit/1d2b1f63fca16699eedc71fb400afd65eefbfed2 
https://github.com/openshift/kubernetes/commit/4aaeaec06c95e0a1a868695792c256d8f0158075
https://github.com/openshift/cloud-provider-azure/commit/8c622c018714685c1ac2a41e4dc44564fbb1d6ba

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/lgtm

**Comment by wgahnagl** [comment]
/retest-required 
 
 The node timed out, retesting to see if it's a flake 
 
 ``` 2023/07/20 05:26:24 1m0.236709983s time is required to configure 1 nodes
    reconfigure_test.go:67: 
        	Error Trace:	/go/src/github.com/openshift/windows-machine-config-operator/test/e2e/reconfigure_test.go:67
        	Error:      	Received unexpected error:
        	            	failed to verify condition type Upgradeable has state True: timed out waiting for the condition
        	Test:       	TestWMCO/reconfigure/Reconfigure_instance
        	Messages:   	operator Upgradeable condition not in proper state  ```

**Comment by aravindhp** [comment]
/hold cancel
/retest-required

wicd-unit-vsphere is [failing](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1692/pull-ci-openshift-windows-machine-config-operator-master-wicd-unit-vsphere/1681870096147943424) with:
```
2023-07-20 04:01:21+00:00 - Finding template windows-golden-images/windows-server-2022-template-ipv6-disabled-with-docker in vCenter...
2023-07-20 04:01:21+00:00 - Exiting, template windows-golden-images/windows-server-2022-template-ipv6-disabled-with-docker not found in vCenter 
```
@wgahnagl If this continues please escalate

**Pull request merged**
