### PR TITLE
[release-4.14] OCPBUGS-22984: Introduce upgrading label to block concurrent upgrades

### PR DESCRIPTION
**Pull request by jrvaldes**
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1901

### CODE REVIEW

**Comment by jrvaldes** [comment]
vsphere-e2e-upgrade   [failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1926/pull-ci-openshift-windows-machine-config-operator-release-4.14-vsphere-e2e-upgrade/1721888611659419648) with 

```
2023-11-07T16:19:23Z	INFO	controller.windowsmachine	node upgrade has been blocked, as it can not be ensured that workloads will not be disrupted. If an in-tree persistent storage volume is in use, please ensure the CSI drivers for the given node have been deployed. This block must be overriden by applying the label windowsmachineconfig.openshift.io/allow-upgrade=true to the node. It is recommended to unblock Nodes individually, and to wait for the upgrade to complete sucessfully before unblocking another Node.
```

**Comment by mtnbikenc** [comment]
/hold
Until after 8.1.1

**Pull request merged**
