### PR TITLE
[release-4.12] WINC-1001: [wmco] Use standard library errors package

### PR DESCRIPTION
**Pull request by alinaryan**
Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1512

### CODE REVIEW

**Comment by alinaryan** [comment]
/retest-required 

Windows node creation failure 

`    create_test.go:202: 
        	Error Trace:	/go/src/github.com/openshift/windows-machine-config-operator/test/e2e/create_test.go:202
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestWMCO/create/Creation/ConfigMap_controller/VM_is_configured_by_ConfigMap_controller
        	Messages:   	Windows node creation failed`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1548/pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator/1645529279770923008

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

did a comparison to the cherry-pick

**Comment by mtnbikenc** [comment]
/hold
The automatic cherry-pick should be tried again after backporting other PRs.

**Pull request closed without merging**
