### PR TITLE
[release-4.12] submodule update 08/30

### PR DESCRIPTION
**Pull request by alinaryan**
- [[submodule][kube-proxy] Update to 08ff87bfdab](https://github.com/openshift/windows-machine-config-operator/pull/1761/commits/716beb8bf7d56d997256709a2ae8205d96146e77) 
- [[build] Update kube-proxy version to v1.25.4+08ff87bf](https://github.com/openshift/windows-machine-config-operator/pull/1761/commits/d4504f1a62e88da4ece80c5b8294eb1bec0f005d)

### CODE REVIEW

**Comment by aravindhp** [comment]
@alinaryan is there a reason the containerd submodule is not getting updated? I see the submodule is at 1.6.19 but the repo is at [v1.6.23](https://github.com/openshift/containerd/releases/tag/v1.6.23).

**Comment by aravindhp** [comment]
If I run the script I am seeing the following commits:
* e03731be (HEAD -> release-4.12-submodule-update-08-30) [submodule][cloud-provider-azure] Update to 8bc8af271 <Aravindh Puthiyaparambil> (64 seconds ago)
* 6cfdbbd4 [submodule][hcsshim] Update to 9cd2a016 <Aravindh Puthiyaparambil> (65 seconds ago)
* 2b64a11c [build] Update containerd version to v1.6.23-6-g1a347cc63 <Aravindh Puthiyaparambil> (65 seconds ago)
* 96420ae3 [submodule][containerd] Update to 1a347cc63 <Aravindh Puthiyaparambil> (67 seconds ago)
* 0eb04bbf [build] Update kubelet version to v1.25.12+26bab08 <Aravindh Puthiyaparambil> (77 seconds ago)
* 32ad3385 [submodule][kubelet] Update to 26bab08d8df <Aravindh Puthiyaparambil> (81 seconds ago)
* 0d4f3373 [submodule][promu] Update to d5383c5 <Aravindh Puthiyaparambil> (84 seconds ago)
* e262774a [submodule][ovn-kubernetes] Update to ac22a205a <Aravindh Puthiyaparambil> (88 seconds ago)

**Comment by mansikulkarni96** [comment]
I had asked @alinaryan to update the kube-proxy submodule branch as we are lagging behind on it.
@alinaryan If your other commits are overwritten and the branch is re-created when you execute the hack script remote branch update command, you could cherry-pick this commit or create a different PR for this change.

**Comment by aravindhp** [comment]
Updating the  kube-proxy submodule branch shouldn't preclude updating the other submodules. The hack script is smart enough to handle that.
```
hack/update_submodules.sh -m kube-proxy -r sdn-4.12-kubernetes-1.25.4 release-4.12
```
This will create `release-4.12-submodule-update-08-30`. 

You can then do:
```
git checkout release-4.12-submodule-update-08-30
hack/update_submodules.sh release-4.12-submodule-update-08-30
```
This will create `release-4.12-submodule-update-08-30-submodule-update-08-30` against which you can open the PR.

**Comment by alinaryan** [comment]
Thank you @aravindhp I will run that command or cherry-pick as @mansikulkarni96 suggested.

**Pull request closed without merging**
