### PR TITLE
[build] Build CNI plugins from downstream

### PR DESCRIPTION
**Pull request by aravindhp**
Instead of using the CNI plugins from an upstream release, build it from the downstream OpenShift repo.

### CODE REVIEW

**Review by LorbusChris — APPROVED** [review]

**Review by LorbusChris — APPROVED** [review]
One thing that might be helpful on the CI Dockerfile is to add `RUN git rev-parse HEAD` on each of the build containers that check out an external repo.

**Comment by mansikulkarni96** [comment]
LGTM

**Review by ravisantoshgudimetla — APPROVED** [review]
/approve

Thank you for working on this @aravindhp

**Comment by aravindhp** [comment]
> One thing that might be helpful on the CI Dockerfile is to add `RUN git rev-parse HEAD` on each of the build containers that check out an external repo.

Good point. I would rather do that in a separate PR across all our dependencies.

**Pull request merged**
