### PR TITLE
[master][submodule] Update 10/19

### PR DESCRIPTION
**Pull request by jrvaldes**
[submodule][windows-machine-config-bootstrapper] Update to https://github.com/openshift/windows-machine-config-bootstrapper/commit/391123dfbd7bc1212afedde967bccae9c34e6ca7

  
[submodule][ovn-kubernetes] Update to https://github.com/openshift/ovn-kubernetes/commit/1992b7d4f5dacac6380d52bf74947f3c80fa78ca

  
[submodule][containernetworking-plugins] Update to https://github.com/openshift/containernetworking-plugins/commit/a80f92c712d2ead4093585fdc627ab28ccf4ae18

  
[submodule][kubelet] Update to https://github.com/openshift/kubernetes/commit/588303cf45990e14050880e595d4b0cca949188b

  
[submodule][cloud-provider-azure] Update to https://github.com/openshift/cloud-provider-azure/commit/6ff1c8e52ad75cb72682b022952c174a41c1e471

Ran:
```
./hack/update_submodules.sh master
```

### CODE REVIEW

**Comment by jrvaldes** [comment]
Supersedes:
- https://github.com/openshift/windows-machine-config-operator/pull/1262

**Review by aravindhp — APPROVED** [review]

**Comment by jrvaldes** [comment]
/test vsphere-e2e-operator

timed out waiting for the condition on clusteroperators/network

**Pull request merged**
