### PR TITLE
[release-4.8][submodule] Update 10/27

### PR DESCRIPTION
**Pull request by jrvaldes**
[submodule][windows-machine-config-bootstrapper] Update to https://github.com/openshift/windows-machine-config-bootstrapper/commit/21a6a9cdc3d2d4462107fb5f9d5a7a7e88353878
  
[submodule][ovn-kubernetes] Update to https://github.com/openshift/ovn-kubernetes/commit/345e744a691a7ba8fc5043d3a0005e06e9746a89
  
[submodule][kube-proxy]  Update to https://github.com/openshift/kubernetes/commit/00b176cc567eaf6911dec2bd417e008e93ac51fb

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]

**Comment by mtnbikenc** [comment]
/hold
Merging to release-4.8 should be blocked until the release of WMCO 3.1.2.

**Comment by mtnbikenc** [comment]
Dropping hold in favor of https://github.com/openshift/windows-machine-config-operator/issues/1299
/hold cancel

**Pull request merged**
