### PR TITLE
[WNI] Combine unnecessary AWS structs

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
As of now, we don't need the `AWSOpts` and `createFlagInfo` structs within
`cmd/aws.go` as both of them are being bound from the user provided command
line options, so collapsing them into a single structure

/cc @aravindhp @Bowenislandsong

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
Thanks for reviewing @aravindhp. I need your lgtm :)

**Comment by aravindhp** [comment]
Let @Bowenislandsong lgtm and I will lgtm given his code is being changed

**Comment by ravisantoshgudimetla** [comment]
> Let @Bowenislandsong lgtm and I will lgtm given his code is being changed

Ok, fine by me 👍

**Comment by Bowenislandsong** [comment]
Since this commit changes parameters passing of the flags, I have tested manually to see if everything works. 
```[bowensong@localhost windows-machine-config-operator]$ ./wni aws create --kubeconfig /home/bowensong/dev/openshift/installer/cluster0/auth/kubeconfig  --credentials=~/.aws/credentials --credential-account=default --image-id ami-0943eb2c39917fc11 --instance-type m4.large --ssh-key libra 
2019-10-02T11:26:21.623-0400	INFO	client	zapr@v0.1.0/zapr.go:69	kubeconfig source: /home/bowensong/dev/openshift/installer/cluster0/auth/kubeconfig
2019-10-02T11:26:55.115-0400	INFO	aws-ec2	zapr@v0.1.0/zapr.go:69	Successfully created windows instance: i-056778de1a1369daf, please RDP into the Windows instance.
```
```[bowensong@localhost windows-machine-config-operator]$ ./wni aws destroy --kubeconfig /home/bowensong/dev/openshift/installer/cluster0/auth/kubeconfig  --credentials=~/.aws/credentials --credential-account=default
2019-10-02T11:30:48.281-0400	INFO	client	zapr@v0.1.0/zapr.go:69	kubeconfig source: /home/bowensong/dev/openshift/installer/cluster0/auth/kubeconfig
2019-10-02T11:30:48.433-0400	INFO	aws-ec2	zapr@v0.1.0/zapr.go:69	processing file '/home/bowensong/go/src/github.com/openshift/windows-machine-config-operator/windows-node-installer.json'
```

**Pull request merged**
