### PR TITLE
WINC-474 : [community-4.6] Configure Prometheus to scrape exposed metric Endpoint

### PR DESCRIPTION
**Pull request by VaishnaviHire**
Backporting #142

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/approve

**Comment by aravindhp** [comment]
/hold

OKD cluster is consistently failing to come up

```
level=warning msg="Missing permissions to fetch Quotas and therefore will skip checking them: failed to load limits for servicequotas: failed to list default serviceqquotas for ec2: AccessDeniedException: User: arn:aws:iam::460538899914:user/origin-ci-robot-provision is not authorized to perform: servicequotas:ListAWSDefaultServiceQuotas, make sure you have `servicequotas:ListAWSDefaultServiceQuotas` persmission available to the user."
66
level=info msg="Creating infrastructure resources..."
67
level=info msg="Waiting up to 20m0s for the Kubernetes API at https://api.ci-op-mnbs5q02-e3e66.origin-ci-int-aws.dev.rhcloud.com:6443..."
68
level=error msg="Attempted to gather ClusterOperator status after installation failure: listing ClusterOperator objects: Get \"https://api.ci-op-mnbs5q02-e3e66.origin-ci-int-aws.dev.rhcloud.com:6443/apis/config.openshift.io/v1/clusteroperators\": dial tcp 75.101.181.242:6443: connect: connection refused"
69
level=info msg="Pulling debug logs from the bootstrap machine"
70
level=info msg="Bootstrap gather logs captured here \"/tmp/installer/log-bundle-20201121121134.tar.gz\""
71
level=fatal msg="Bootstrap failed to complete: failed waiting for Kubernetes API: Get \"https://api.ci-op-mnbs5q02-e3e66.origin-ci-int-aws.dev.rhcloud.com:6443/version?timeout=32s\": dial tcp 54.147.155.168:6443: connect: connection refused"
72
2020/11/21 12:11:38 Failed to upload $KUBECONFIG: timed out waiting for the condition
73
error: failed to execute wrapped command: exit status 1
```

**Comment by LorbusChris** [comment]
The same issue occurred [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_coredns/46/pull-ci-openshift-coredns-master-e2e-aws/1328687895002746880) and went away eventually without further doing. Let's try again..
/retest

**Pull request merged**
