### PR TITLE
[release-4.14] WINC-1300: Update version to 9.0.4

### PR DESCRIPTION
**Pull request by sebsoto**
This commit was generated by hack/pre-release.sh

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by sebsoto** [comment]
/override ci/prow/aws-e2e-operator ci/prow/aws-e2e-upgrade ci/prow/azure-e2e-operator ci/prow/azure-e2e-upgrade ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator ci/prow/vsphere-e2e-operator ci/prow/wicd-unit-vsphere

**Comment by sebsoto** [comment]
/override ci/prow/aws-e2e-operator  ci/prow/azure-e2e-operator ci/prow/azure-e2e-upgrade ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator ci/prow/vsphere-e2e-operator ci/prow/wicd-unit-vsphere

**Comment by sebsoto** [comment]
/override ci/prow/aws-e2e-operator ci/prow/azure-e2e-operator ci/prow/vsphere-e2e-upgrade ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator ci/prow/vsphere-e2e-operator ci/prow/wicd-unit-vsphere

**Pull request merged**
