### PR TITLE
WINC-923: bumps pause image from 3.6 to 3.9

### PR DESCRIPTION
**Pull request by wgahnagl**
bumps pause image to 3.9

### CODE REVIEW

**Comment by saifshaikh48** [comment]
/lgtm

:rocket:

**Comment by aravindhp** [comment]
@wgahnagl Please follow the existing pattern and use `WINC-923:` instead of `[WINC-923]. You also don't need the Jira prefix in the commit message. Using it in Just the PR header will suffice.

**Review by aravindhp — APPROVED** [review]
Thanks for working on this, @wgahnagl

**Comment by mtnbikenc** [comment]
Error creating cluster.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1371/pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade/1615117856737857536#1:build-log.txt%3A128
```
level=error msg=Error: creating EC2 Instance: InvalidParameterValue: Value (ci-op-mzjqppxs-4bc28-gdbmr-bootstrap-profile) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
```
Could be related to https://issues.redhat.com/browse/OCPBUGS-678
/retest-required

**Comment by saifshaikh48** [comment]
Now that https://github.com/openshift/windows-machine-config-operator/pull/1389 has merged, all backports can be opened (back to `release-4.9`).

**Comment by aravindhp** [comment]
@wgahnagl this has to be cherry-picked to release-4.10 and release-4.9 also.

**Comment by aravindhp** [comment]
@wgahnagl looks like you need to open a manual backport to release-4.10. You can do a cherry-pick of that PR into `release-4.9`.

**Comment by aravindhp** [comment]
@wgahnagl a heads up that for release-4.10 and release-4.9 you have to update the pause image in the [windows-machine-config-bootstrapper](https://github.com/openshift/windows-machine-config-bootstrapper) repo. Please reach out to the team if you need any help with that.

**Pull request merged**
