### PR TITLE
[release-4.13] submodule update 08/05

### PR DESCRIPTION
**Pull request by sebsoto**
Update to https://github.com/openshift/ovn-kubernetes/commit/4748eb6192d4615b1608429dd5f6d906ccbdbc38

This commit was generated using hack/update_submodules.sh

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by sebsoto** [comment]
/override "Red Hat Konflux / windows-machine-config-operator-release-4-13-on-pull-request"

**Comment by sebsoto** [comment]
/override "Red Hat Konflux / windows-machine-config-operator-release-4-13-on-pull-request"

**Pull request closed without merging**
