### PR TITLE
[build] Fix OVN repository name in Dockerfiles

### PR DESCRIPTION
**Pull request by aravindhp**
Also fix a spelling error in the Dockerfile given it is in the same area

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
Was it failing locally for you without this fix?

**Comment by aravindhp** [comment]
> Was it failing locally for you without this fix?

Yes.

**Comment by aravindhp** [comment]
Strangely this is not happening today. So it might have been a flake.

**Pull request closed without merging**
