### PR TITLE
Add goio to linter

### PR DESCRIPTION
**Pull request by aravindhp**
Add [go-imports-organizer/goio](https://github.com/go-imports-organizer/goio) to the linter

### CODE REVIEW

**Review by sebsoto — APPROVED** [review]

**Comment by aravindhp** [comment]
/test vsphere-e2e-operator

[Failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1596/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator/1653142131750998016) with:
```
 waiting for api to be available
level=error
level=error msg=Error: failed to upload: Post "https://10.3.32.4/nfc/526d4297-43ed-0611-4d0c-aa1899142782/disk-0.vmdk": tls: failed to verify certificate: x509: certificate signed by unknown authority
level=error
level=error msg=  with vsphereprivate_import_ova.import[0],
level=error msg=  on main.tf line 70, in resource "vsphereprivate_import_ova" "import":
level=error msg=  70: resource "vsphereprivate_import_ova" "import" {
level=error
level=error msg=failed to fetch Cluster: failed to generate asset "Cluster": failure applying terraform for "pre-bootstrap" stage: failed to create cluster: failed to apply Terraform: exit status 1
level=error
level=error msg=Error: failed to upload: Post "https://10.3.32.4/nfc/526d4297-43ed-0611-4d0c-aa1899142782/disk-0.vmdk": tls: failed to verify certificate: x509: certificate signed by unknown authority
level=error
level=error msg=  with vsphereprivate_import_ova.import[0],
level=error msg=  on main.tf line 70, in resource "vsphereprivate_import_ova" "import":
level=error msg=  70: resource "vsphereprivate_import_ova" "import" {
level=error
level=error
Installer exit with code 4
```
Hopefully a flake.

**Comment by aravindhp** [comment]
/test azure-e2e-ccm-install

Same error as in https://github.com/openshift/windows-machine-config-operator/pull/1586#issuecomment-1531747186

**Pull request merged**
