### PR TITLE
WINC-1043: Upgrade test improvements

### PR DESCRIPTION
**Pull request by sebsoto**
Includes various fixes/improvements for the new upgrade test

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]

**Comment by aravindhp** [comment]
/hold

For https://github.com/openshift/windows-machine-config-operator/pull/1725

**Comment by mtnbikenc** [comment]
GCP job is blocked by https://issues.redhat.com/browse/OCPBUGS-17731
/override ci/prow/gcp-e2e-operator

**Comment by aravindhp** [comment]
Blocked by https://github.com/openshift/windows-machine-config-operator/pull/1744

**Comment by jrvaldes** [comment]
> @mansikulkarni96: #1733 failed to apply on top of branch "release-4.12":
> 
> ```
> Applying: Fix cleanup for new upgrade test
> Applying: Fix workloadAvailable test
> Using index info to reconstruct a base tree...
> M	test/e2e/upgrade_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging test/e2e/upgrade_test.go
> CONFLICT (content): Merge conflict in test/e2e/upgrade_test.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0002 Fix workloadAvailable test
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

Opened:

- https://github.com/openshift/windows-machine-config-operator/pull/2050

**Pull request merged**
