### PR TITLE
[release-4.7][docs] DeploymentConfig limitation

### PR DESCRIPTION
**Pull request by mansikulkarni96**
(cherry picked from commit 53e82e4d36d7edc4b658685cd19ad8ee629692bb)

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/lgtm

**Comment by aravindhp** [comment]
/hold

as I see some discussion between @sebsoto and @mansikulkarni96

**Comment by aravindhp** [comment]
/hold cancel

Oops the hold was too late 😄

**Comment by mansikulkarni96** [comment]
Np @aravindhp as the manifests directory structure differs between 4.7 and master, this one could not have been cherry-picked cleanly.

**Pull request merged**
