### PR TITLE
WINC-805: Add support for Windows Server 2022 in AWS

### PR DESCRIPTION
**Pull request by aravindhp**
Update to https://github.com/openshift/ovn-kubernetes/commit/a2eb4c392dce404b578f12e65c971d4c836c04f2 which will pick up the fix for [OCPBUGS-12971](https://issues.redhat.com/browse/OCPBUGS-12971).  The fix will prevent hybrid-overlay from overwriting the non-persistent routes for the metadata endpoint on AWS Windows Server 2022 instances. Once this PR merges, a follow up PR to the release repo will be required to actually start testing Windows Server 2022 on AWS.

### CODE REVIEW

**Review by sebsoto — APPROVED** [review]

**Comment by alinaryan** [comment]
LGTM

**Comment by aravindhp** [comment]
/test nutanix-e2e-operator 

[Failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1604/pull-ci-openshift-windows-machine-config-operator-master-nutanix-e2e-operator/1654541074724556800) during bootstrapping:
```
E0505 18:47:19.869489    1515 reflector.go:140] k8s.io/client-go/tools/watch/informerwatcher.go:146: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://api.ci-op-p1sttwmy-5c595.nutanix-ci.devcluster.openshift.com:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dbootstrap&resourceVersion=5318": tls: failed to verify certificate: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, openshift, openshift.default, openshift.default.svc, openshift.default.svc.cluster.local, 10.128.0.1, not api.ci-op-p1sttwmy-5c595.nutanix-ci.devcluster.openshift.com
```

**Comment by aravindhp** [comment]
/hold

For https://github.com/openshift/windows-machine-config-operator/pull/1586 to merge as we can't test https://github.com/openshift/release/pull/39069 without that

**Comment by aravindhp** [comment]
/unhold

#1586 is having issues that need to be investigated

**Comment by aravindhp** [comment]
/retest-required

Took too long to get a GCP lease and the test hit the 4 hour limit

**Pull request merged**
