### PR TITLE
[release-4.14] WINC-1310: Remove certain tests in old upgrade suite

### PR DESCRIPTION
**Pull request by saifshaikh48**
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/2249

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by saifshaikh48** [comment]
/retest-required

looks like some flakes but slight concern about some CSR approval failures on vSphere

**Comment by saifshaikh48** [comment]
reverse DNS lookup issues on vSphere blocking this, awaiting bug fix https://github.com/openshift/windows-machine-config-operator/pull/2256

**Comment by saifshaikh48** [comment]
/retest-required

PR was in the tide merge queue with every test having passed before all tests got kicked off again... retesting these failures once more before asking for overrides

**Comment by saifshaikh48** [comment]
/retest-required

vsphere infra issues

**Comment by mansikulkarni96** [comment]
/override ci/prow/platform-none-vsphere-e2e-operator ci/prow/wicd-unit-vsphere

**Pull request merged**
