### PR TITLE
Submodule update 07/25

### PR DESCRIPTION
**Pull request by alinaryan**
[submodule][promu] Update to 6c8c415

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Review by aravindhp — APPROVED** [review]

**Comment by alinaryan** [comment]
/test azure-e2e-operator

Flake: 
TestWMCO/create/UserData_validation/Update_the_userdata_secret_with_invalid_data timeout occurred before the node was ready. 

`error waiting for Machine nodes to be reconfigured`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1701/pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-operator/1683888423028396032

**Comment by alinaryan** [comment]
/test gcp-e2e-operator

TestWMCO/create/Creation/Machine_controller timeout occured because node took 35 mins to configure 
    create_test.go:178: 

`Windows node creation failed`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1701/pull-ci-openshift-windows-machine-config-operator-master-gcp-e2e-operator/1683888423158419456

**Comment by alinaryan** [comment]
/test vsphere-e2e-operator

Related to: https://redhat-internal.slack.com/archives/C015H2WDJRY/p1690378611448979

**Comment by mtnbikenc** [comment]
/unhold
vsphere jobs are passing now

**Comment by aravindhp** [comment]
/override ci/prow/aws-e2e-upgrade ci/prow/aws-e2e-operator

AWS jobs are failing at the step. This submodule update only touches Promu that too a owners file addition. It can be safely overridden.

**Pull request merged**
