### PR TITLE
[release-4.9][docs] DeploymentConfig limitation

### PR DESCRIPTION
**Pull request by mansikulkarni96**
(cherry picked from commit 53e82e4d36d7edc4b658685cd19ad8ee629692bb)

### CODE REVIEW

**Comment by sebsoto** [comment]
@mansikulkarni96 if possible could you use the bot to cherry-pick this one to the remaining release branches? Not super important, but looks like this one will cherry-pick cleanly.

**Comment by mansikulkarni96** [comment]
@sebsoto when I tried the cherry-picks locally they did not go through in a clean way . I had to resolve the conflicts manually for 4.8 and 4.7 as well. The newly added community description.md file was the cause of the conflicts.

**Review by aravindhp — APPROVED** [review]
/lgtm

**Pull request merged**
