### PR TITLE
WINC-924: Move deprecated command line flags to KubeletConfiguration

### PR DESCRIPTION
**Pull request by jrvaldes**
This PR removes the deprecated kubelet command line arguments and adds them to the KubeletConfiguration
object as recommended by [upstream docs.](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/)

### CODE REVIEW

**Comment by jrvaldes** [comment]
azure-e2e-upgrade [passed](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_windows-machine-config-operator/2048/pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-upgrade/1752083865750474752)

**Comment by alinaryan** [comment]
Thanks for working on this
LGTM
How did you test? Can you add the mentioned upstream docs to the description?

**Comment by jrvaldes** [comment]
>  How did you test? 
Running e2e 
https://github.com/openshift/windows-machine-config-operator/pull/2048#issuecomment-1917262573

> Can you add the mentioned upstream docs to the description?
Done

**Review by sebsoto — APPROVED** [review]

**Pull request merged**
