### PR TITLE
[release-4.16] submodule update 08 12

### PR DESCRIPTION
**Pull request by wgahnagl**
[[submodule][ovn-kubernetes] Update to b0250b9f4](https://github.com/openshift/windows-machine-config-operator/commit/f1b209bcd0c79256f253c4f6e43886aeb53e224d)
[[vendor] Use v1.29.7+6abe8a1 k8s and OpenShift libraries](https://github.com/openshift/windows-machine-config-operator/commit/1108cf7a724695c0b1c31e1a8ae6758bd600bd54)

### CODE REVIEW

**Review by mansikulkarni96 — APPROVED** [review]

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by jrvaldes** [comment]
/close

in favor of
- https://github.com/openshift/windows-machine-config-operator/pull/2385

**Pull request closed without merging**
