### PR TITLE
[release-4.8] Prep for 3.1.0 release

### PR DESCRIPTION
**Pull request by mansikulkarni96**
This PR updates the WMCO version to v3.1.0 and for the next 4.8 operator release.

### CODE REVIEW

**Comment by aravindhp** [comment]
Shouldn't you cherry-pick #580?

**Comment by mansikulkarni96** [comment]
@aravindhp there was a conflict in bundle manifests with the [pre-requisites](https://github.com/openshift/windows-machine-config-operator/blob/92ec7a4340e3986518f1c086e14d5a9f83b92888/bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml#L38) spelling correction I made.
cherry-pick [failed](https://github.com/openshift/windows-machine-config-operator/pull/580#issuecomment-903127956).
Here I am cherry-picking the individual commits.

**Comment by aravindhp** [comment]
Why was there a conflict wrt the prerequisite spelling error? Did we miss back porting some other PR?

**Comment by mansikulkarni96** [comment]
@aravindhp no that change was part of #580

**Review by aravindhp — APPROVED** [review]
/approve

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Pull request merged**
