### PR TITLE
[release-4.16] submodule update 08 19

### PR DESCRIPTION
**Pull request by jrvaldes**
Ran:

```
./hack/update_submodules.sh release-4.16

```

### CODE REVIEW

**Comment by jrvaldes** [comment]
/hold

blocked by  windows_exporter release-4.16 branch creation.

**Comment by jrvaldes** [comment]
/hold cancel

windows_exporter release-4.16 branch created 

https://github.com/openshift/prometheus-community-windows_exporter/tree/release-4.16

**Comment by sebsoto** [comment]
Out of date, should be closed

**Pull request closed without merging**
