### PR TITLE
[windows_exporter] Update submodule

### PR DESCRIPTION
**Pull request by LorbusChris**
Updates the windows_exporter submodule to commit
ab524f0a961589e25c968607ff603e4807f33815.

Commands run:
```
cd windows_exporter
git pull
cd ..
```

This commit of windows_exporter contains a vendor dir with all its dependencies, which is needed for builds in Brew.

Requires switching this repo to Go 1.15

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/approve

**Comment by LorbusChris** [comment]
This may actually still be buildable with Go 1.14, so not exactly sure we need to block on that.
/hold
for now

**Comment by aravindhp** [comment]
/hold cancel

Confirmed that vendoring works:
```
Building binary: windows_exporter
 >   windows_exporter.exe
Building binary: go build -o windows_exporter.exe -ldflags -X github.com/prometheus/common/version.Version= -X github.com/prometheus/common/version.Revision=non-git -X github.com/prometheus/common/version.Branch=non-git -X github.com/prometheus/common/version.BuildUser=root@446b386058ad -X github.com/prometheus/common/version.BuildDate=20201113-21:37:21  -extldflags '-static' -mod=vendor github.com/prometheus-community/windows_exporter
 +  go build -o windows_exporter.exe -ldflags -X github.com/prometheus/common/version.Version= -X github.com/prometheus/common/version.Revision=non-git -X github.com/prometheus/common/version.Branch=non-git -X github.com/prometheus/common/version.BuildUser=root@446b386058ad -X github.com/prometheus/common/version.BuildDate=20201113-21:37:21  -extldflags '-static' -mod=vendor github.com/prometheus-community/windows_exporter
```

**Pull request merged**
