### PR TITLE
Bug 1757446: [wni] Directory validation errors

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Took over the work from https://github.com/openshift/windows-machine-config-operator/pull/35, I addressed the comments I made https://github.com/openshift/windows-machine-config-operator/pull/35/files#r330166016 and here https://github.com/openshift/windows-machine-config-operator/pull/35/files#r330165612 and added a test suite

I am preserving Bowen's commit to not take credit for some part of his work.

/cc @aravindhp @Bowenislandsong

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
Output of running unit tests locally:

```go
go test $(go list github.com/openshift/windows-machine-config-operator/tools/windows-node-installer/pkg...) -v
?   	github.com/openshift/windows-machine-config-operator/tools/windows-node-installer/pkg/client	[no test files]
=== RUN   TestMakeValidAbsPath
--- PASS: TestMakeValidAbsPath (0.00s)
PASS
ok  	github.com/openshift/windows-machine-config-operator/tools/windows-node-installer/pkg/cloudprovider	0.010s
?   	github.com/openshift/windows-machine-config-operator/tools/windows-node-installer/pkg/cloudprovider/aws	[no test files]
=== RUN   TestAppendInstallerInfo
--- PASS: TestAppendInstallerInfo (0.00s)
=== RUN   TestReadInstallerInfo
--- PASS: TestReadInstallerInfo (0.00s)
=== RUN   TestRemoveInstallerInfo
--- PASS: TestRemoveInstallerInfo (0.00s)
=== RUN   TestMakeFilePath
--- PASS: TestMakeFilePath (0.00s)
PASS
ok  	github.com/openshift/windows-machine-config-operator/tools/windows-node-installer/pkg/resource	(cached)

```

**Comment by Bowenislandsong** [comment]
/lgtm
/hold
@ravisantoshgudimetla  do you think we could have ```bash GO111MODULE=on go test $(go list github.com/openshift/windows-machine-config-operator/tools/windows-node-installer/pkg...) -v``` in the make file?  Since this is adding unit test?

**Comment by ravisantoshgudimetla** [comment]
> /lgtm
> /hold
> @ravisantoshgudimetla do you think we could have `bash GO111MODULE=on go test $(go list github.com/openshift/windows-machine-config-operator/tools/windows-node-installer/pkg...) -v` in the make file? Since this is adding unit test?

I think we already have a jira story around this, https://github.com/openshift/windows-machine-config-operator/pull/28, are you asking we should increase the priority of that story now? If yes, I am fine with it however it should go in a separate PR is what I am thinking.

**Comment by Bowenislandsong** [comment]
> > /lgtm
> > /hold
> > @ravisantoshgudimetla do you think we could have `bash GO111MODULE=on go test $(go list github.com/openshift/windows-machine-config-operator/tools/windows-node-installer/pkg...) -v` in the make file? Since this is adding unit test?
> 
> I think we already have a jira story around this, #28, are you asking we should increase the priority of that story now? If yes, I am fine with it however it should go in a separate PR is what I am thinking.

You are right, and I should not 'unconsciously' sneak in code. This is just a bug fix and it is good. Thank you. 

/hold cancel

**Pull request merged**
