### PR TITLE
[wicd] Pass klog to controller-runtime

### PR DESCRIPTION
**Pull request by sebsoto**
This commit removes all unecessary klog calls and passes a klog logger into the controller-runtime manager, causing reconcile errors to be logged automatically, instead of having to make extra klog.Error() calls.

### CODE REVIEW

**Comment by sebsoto** [comment]
Excerpt from WICD logs with this change:
```
I0323 13:18:30.242444    1768 controller.go:291] successfully reconciled service hybrid-overlay-node
I0323 13:18:30.242444    1768 controller.go:286] reconciling existing service kube-proxy
E0323 13:18:31.722340    1768 controller.go:326] "Reconciler error" err=<
	could not resolve PowerShell variable ENDPOINT_IP: error running command with output New-HnsEndpoint : Cannot process argument transformation on parameter 'NetworkId'. Cannot convert null to type 
	"System.Guid".
	At C:\Temp\network-conf.ps1:76 char:44
	+     $endpoint = New-HnsEndpoint -NetworkId $hns_network.ID -Name "VIP ...
	+                                            ~~~~~~~~~~~~~~~
	    + CategoryInfo          : InvalidData: (:) [New-HnsEndpoint], ParentContainsErrorRecordException
	    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-HnsEndpoint
	 
	: exit status 1
 > controller="node" controllerGroup="" controllerKind="Node" node="winworker-tnbjk" namespace="" name="winworker-tnbjk" reconcileID=4039ae5d-eca3-4872-bd2a-89706e17a41a

```

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

thanks for doing this, new output looks quite readable

**Review by aravindhp — APPROVED** [review]
Cool!

**Pull request merged**
