### PR TITLE
[submodules] Update k8s, OVN and CNI to release-4.8

### PR DESCRIPTION
**Pull request by aravindhp**

### CODE REVIEW

**Comment by VaishnaviHire** [comment]
@aravindhp Dow we also need to update `windows_exporter` here ?

**Comment by aravindhp** [comment]
> @aravindhp Dow we also need to update `windows_exporter` here ?

@VaishnaviHire I only want to update the Kubernetes components here. `windows_exporter` update to the next version should be a separate PR.

**Comment by aravindhp** [comment]
/test aws-e2e-operator

Cluster failed to come up:
```
level=error msg=Cluster operator authentication Degraded is True with APIServerDeployment_UnavailablePod::IngressStateEndpoints_MissingSubsets::OAuthServerConfigObservation_Error::OAuthServiceCheckEndpointAccessibleController_SyncError::OAuthServiceEndpointsCheckEndpointAccessibleController_SyncError::RouterCerts_NoRouterCertSecret: OAuthServiceCheckEndpointAccessibleControllerDegraded: Get "https://172.30.109.227:443/healthz": dial tcp 172.30.109.227:443: connect: connection refused
level=error msg=OAuthServiceEndpointsCheckEndpointAccessibleControllerDegraded: oauth service endpoints are not ready
level=error msg=RouterCertsDegraded: secret/v4-0-config-system-router-certs -n openshift-authentication: could not be retrieved: secret "v4-0-config-system-router-certs" not found
level=error msg=OAuthServerConfigObservationDegraded: secret "v4-0-config-system-router-certs" not found
level=error msg=APIServerDeploymentDegraded: 2 of 2 requested instances are unavailable for apiserver.openshift-oauth-apiserver (crashlooping container is waiting in apiserver-f7f47749d-lgxnp pod, crashlooping container is waiting in apiserver-f7f47749d-2kls6 pod)
level=error msg=IngressStateEndpointsDegraded: No subsets found for the endpoints of oauth-server 
```

**Pull request merged**
