### PR TITLE
[release-4.10] OCPBUGS-11898: Disable IPv6 on Windows 2022

### PR DESCRIPTION
**Pull request by aravindhp**
- [vpshere_ci] Disable IPv6 on Windows 2022
- [test] Use IPv6 disabled template for Windows 2022

### CODE REVIEW

**Comment by aravindhp** [comment]
/hold

until release-4.12 backport for #1553 is opened

**Comment by aravindhp** [comment]
/retitle [release-4.10] Disable IPv6 on Windows 2022

**Comment by aravindhp** [comment]
/test vsphere-e2e-operator

One of the Windows [Machines](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1554/pull-ci-openshift-windows-machine-config-operator-release-4.10-vsphere-e2e-operator/1646743591554387968/artifacts/vsphere-e2e-operator/gather-extra/artifacts/machines.json) is not getting an address assigned to it and [WMCO](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1554/pull-ci-openshift-windows-machine-config-operator-release-4.10-vsphere-e2e-operator/1646743591554387968/artifacts/vsphere-e2e-operator/gather-extra/artifacts/pods/openshift-windows-machine-config-operator_windows-machine-config-operator-588f665fc7-hzq6g_manager.log) is using a bogus 169 address.

**Comment by aravindhp** [comment]
/test platform-none-vsphere-e2e-operator

[Continuing](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1554/pull-ci-openshift-windows-machine-config-operator-release-4.10-platform-none-vsphere-e2e-operator/1646743591512444928) to see:
```
[14-04-23 05:49:07] Cloning /SDDC-Datacenter/vm/rhcos-410.84.202210040010-0-vmware.x86_64.ova to rhcos-410.84.202210040010-0-vmware.x86_64.ova-hw15...Error: A specified parameter was not correct: spec.location.pool
govc: A specified parameter was not correct: spec.location.pool (Executing prechecks) 
```

**Comment by aravindhp** [comment]
One of the Windows [Machines](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1554/pull-ci-openshift-windows-machine-config-operator-release-4.10-vsphere-e2e-operator/1646918414058393600/artifacts/vsphere-e2e-operator/gather-extra/artifacts/machines.json) did not get assigned an IPv4 address but the other Machine did.

/test vsphere-e2e-operator

**Comment by aravindhp** [comment]
/retitle [release-4.10] OCPBUGS-11898: Disable IPv6 on Windows 2022

**Comment by aravindhp** [comment]
/test platform-none-vsphere-e2e-operator

Still [seeing](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1554/pull-ci-openshift-windows-machine-config-operator-release-4.10-platform-none-vsphere-e2e-operator/1648071416924344320):
```
 2023-04-17 21:46:59+00:00 - Cloning and upgrading rhcos-410.84.202210040010-0-vmware.x86_64.ova to hw version 17...
govc: ServerFaultCode: Permission to perform this operation was denied.
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-04-17T21:46:59Z"}
error: failed to execute wrapped command: exit status 1 
```

**Comment by alinaryan** [comment]
Thanks for working on this, 
/lgtm

**Comment by aravindhp** [comment]
IBM vCenter connections are flaky

/retest-required

**Pull request merged**
