### PR TITLE
[docs] Fix minor typos in HACKING.md

### PR DESCRIPTION
**Pull request by jrvaldes**

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/approve

**Comment by aravindhp** [comment]
/override ci/prow/aws-e2e-operator

Docs PR does not e2e tests to pass.

**Comment by jrvaldes** [comment]
/override ci/prow/aws-e2e-upgrade 
/override ci/prow/azure-e2e-operator
/override ci/prow/vsphere-e2e-operator

Docs PR does not e2e tests to pass.

**Pull request merged**
