### PR TITLE
[release-4.13] OCPBUGS-19084: Restore routes on AWS Windows 2022 nodes

### PR DESCRIPTION
**Pull request by aravindhp**
This is a manual cherry-pick of #1796

### CODE REVIEW

**Comment by aravindhp** [comment]
/retitle  [release-4.13] OCPBUGS-19084: Restore routes on AWS Windows 2022 nodes

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Review by sebsoto — APPROVED** [review]

**Pull request merged**
