### PR TITLE
Master submodule update 08 07

### PR DESCRIPTION
**Pull request by saifshaikh48**
- [[submodule][ovn-kubernetes] Update to f05d79a60](https://github.com/openshift/windows-machine-config-operator/commit/72d5b84ce8b95aa9b9534181d51c5a6f166275ee) 
- [[submodule][kubelet] Update to e12378702b5](https://github.com/openshift/windows-machine-config-operator/commit/c352264693bfcadf4054742bf07be27e4ca8568b) 
- [[build] Update kubelet version to v1.27.4+e123787](https://github.com/openshift/windows-machine-config-operator/commit/932ace3bb15eeb9143bb580127e5a3d3f8bfd30d) 
- [[submodule][hcsshim] Update to 28cce9cea](https://github.com/openshift/windows-machine-config-operator/commit/3b216e9c4211620b57ff309e43edffeef539b700)

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Review by mtnbikenc — APPROVED** [review]

**Comment by saifshaikh48** [comment]
/retest-required

CSR approval failure, hoping it's a flake

**Pull request merged**
