### PR TITLE
Bug 1963263: [submodule][kubernetes] Update to a0b09eb968d

### PR DESCRIPTION
**Pull request by aravindhp**
Update to https://github.com/openshift/kubernetes/commit/a0b09eb968d4ac98e80857e315aff2795fa35825

This commit was generated using hack/update_submodules.sh

Fixes BZ#1963263 by pulling in https://github.com/openshift/kubernetes/pull/763

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by aravindhp** [comment]
/hold

vSphere VMs are not getting created

**Pull request merged**
