### PR TITLE
[release-4.8] Bug 1973580: [submodule][kubelet] Update to 766a5fe58d1

### PR DESCRIPTION
**Pull request by aravindhp**
Update to https://github.com/openshift/kubernetes/commit/766a5fe58d1d9585b1a225b62e91c64b68f69906

Fixes BZ#1973580

### CODE REVIEW

**Comment by aravindhp** [comment]
/retitle [release-4.8] Bug 1973580: [submodule][kubelet] Update to 766a5fe58d1

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by aravindhp** [comment]
/hold

The `aws-e2e-upgrade` test is consistently failing

**Pull request merged**
