### PR TITLE
Master submodule update 10 15

### PR DESCRIPTION
**Pull request by jrvaldes**
Ran:
```
./hack/update_submodules.sh master
```

### CODE REVIEW

**Comment by jrvaldes** [comment]
>go: downloading k8s.io/kube-openapi v0.0.0-20241009091222-67ed5848f094
go: sigs.k8s.io/json@v0.0.0-20241014173422-cfa47c3a1cc8 requires go >= 1.23 (running go 1.22.7; GOTOOLCHAIN=local)
go: sigs.k8s.io/json@v0.0.0-20241014173422-cfa47c3a1cc8 requires go >= 1.23 (running go 1.22.7; GOTOOLCHAIN=local)


kubelet bump requires go >=1.23, we may be blocked until `rhel-9-release-golang-1.23-openshift-4.18` is out.

**Comment by jrvaldes** [comment]
> > go: downloading k8s.io/kube-openapi v0.0.0-20241009091222-67ed5848f094
> > go: sigs.k8s.io/json@v0.0.0-20241014173422-cfa47c3a1cc8 requires go >= 1.23 (running go 1.22.7; GOTOOLCHAIN=local)
> > go: sigs.k8s.io/json@v0.0.0-20241014173422-cfa47c3a1cc8 requires go >= 1.23 (running go 1.22.7; GOTOOLCHAIN=local)
> 
> kubelet bump requires go >=1.23, we may be blocked until `rhel-9-release-golang-1.23-openshift-4.18` is out.

pushed https://github.com/openshift/windows-machine-config-operator/pull/2476/commits/b3975f39cae2e0752f2869157bd88d4ffc26d078 to address this

**Review by mansikulkarni96 — APPROVED** [review]
/lgtm

**Pull request merged**
