### PR TITLE
[master] Bump submodules

### PR DESCRIPTION
**Pull request by sebsoto**
Bumps kubernetes and ovn-kubernetes submodules

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/approve

Is there a reason for the difference in hash length across commits?

**Comment by sebsoto** [comment]
@aravindhp https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---shortlength

The minimum length is 4, the default is the effective value of the core.abbrev configuration variable (see git-config[1]). This is based on the submodule's config

**Comment by mansikulkarni96** [comment]
Thanks for doing this @sebsoto 
/lgtm

**Pull request merged**
