### PR TITLE
[release-4.12] [e2e] Wait for deleted machines in Azure 

### PR DESCRIPTION
**Pull request by jrvaldes**
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1832

### CODE REVIEW

**Comment by jrvaldes** [comment]
@mansikulkarni96  I feel this will merge in order. PTAL and `/hold` as needed.

**Comment by mansikulkarni96** [comment]
Thanks for opening this @jrvaldes 
/lgtm

**Pull request merged**
