### PR TITLE
[release-4.9] Test that Windows pods use cluster DNS

### PR DESCRIPTION
**Pull request by sebsoto**
Removes defunct DNS test and replaces it with a test which ensures that pods can resolve cluster services through DNS.

(cherry picked from commit 38e374f6274b7a8c400eb3c816e3764b6c48e0e4)

### CODE REVIEW

**Comment by aravindhp** [comment]
Creation test suite failed causing the networking tests not to run

/test aws-e2e-operator

**Comment by mtnbikenc** [comment]
WMCO v4 (4.9) development is closed.
/close

**Pull request closed without merging**
