### PR TITLE
WINC-555: [community-4.7][submodule][wmcb] Update to cf60cd7

### PR DESCRIPTION
**Pull request by aravindhp**
Updates the windows-machine-config-bootstrapper submodule to commit openshift/windows-machine-config-bootstrapper@cf60cd7

Commands run:
```shell
git config -f .gitmodules submodule.windows-machine-config-bootstrapper.branch community-4.7
cd windows-machine-config-bootstrapper
git checkout community-4.7
git pull
```

### CODE REVIEW

**Comment by aravindhp** [comment]
/retitle WINC-555: [community-4.7][submodule][wmcb] Update to cf60cd7

**Comment by aravindhp** [comment]
/retest
```
 {"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2021-02-23T23:43:36Z"}
{"component":"entrypoint","file":"prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2021-02-23T23:43:51Z"}
{"component":"entrypoint","error":"process timed out","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-02-23T23:43:51Z"}
error: failed to execute wrapped command: exit status 127 
```

**Review by sebsoto — APPROVED** [review]

**Comment by aravindhp** [comment]
/hold
Continuing to see:
```
 {"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2021-02-24T22:48:37Z"}
{"component":"entrypoint","file":"prow/entrypoint/run.go:255","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 15s grace period","severity":"error","time":"2021-02-24T22:48:52Z"}
{"component":"entrypoint","error":"process timed out","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-02-24T22:48:52Z"}
error: failed to execute wrapped command: exit status 127 
```
This is happening during the upgrade tests.

**Comment by aravindhp** [comment]
I suspect that the boskos lease is not getting updated and job is getting killed prematurely:
```
 2021/02/24 22:32:38 warning: failed to update lease "us-west-1--29": [Post "https://boskos-ci.apps.ci.l2s4.p1.openshiftapps.com/update?name=us-west-1--29&owner=ci-op-q7gbwln9-3ad70&state=leased": EOF, status 503 Service Unavailable, status code 503 updating us-west-1--29]
2021/02/24 22:32:52 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:33:08 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:33:38 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:34:08 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:34:38 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:35:08 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:35:38 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:36:08 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:36:38 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:37:08 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:37:38 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:38:08 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29
2021/02/24 22:38:38 warning: failed to update lease "us-west-1--29": status 503 Service Unavailable, status code 503 updating us-west-1--29 
```
🤷🏾‍♂️

**Comment by aravindhp** [comment]
/hold

The upgrade test is consistently timing out and requires investigation. This has nothing to do with this PR and I suspect some change on the OKD side is causing this. Same behavior is seen with #322.

**Comment by aravindhp** [comment]
/retest

Test passed for #324

**Pull request merged**
