### PR TITLE
[submodule] update 06/23

### PR DESCRIPTION
**Pull request by alinaryan**
[[submodule][ovn-kubernetes] Update to fb1c5655e](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/b02eb553f6af875ed2263164c2af844e6bf5bdd5)
[[submodule][containernetworking-plugins] Update to 6e00b54](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/b7c2436dae4b9aea9b803dd0dcf5ba40a9053be6)
[[submodule][kubelet] Update to cb4b47e5ddf](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/77e3794ca263fdfa039a817ea540655710714dd3)
[[build] Update kubelet version to v1.27.3+cb4b47e](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/2e37abba20b545d82398d49ace7df0e5fd3ccc8c)
[[submodule][kube-proxy] Update to 70821f71879](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/564bb7b3a4c0d3f83fb366a62688bec762a9a76b)
[[build] Update kube-proxy version to v1.27.1+70821f7](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/492717d6c513b94b3e3f9547d00b4ae461a99175)
[[submodule][containerd] Update to 0cae528dd](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/310440715c13167487bcfca62fb2844ef99be9f7)
[[build] Update containerd version to v1.7.2](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/1e202c8788f52a25a8f302445391774787ac4881)
[[submodule][hcsshim] Update to 8fa2489f](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/c3486b57e615e002c1022cf9b00beb614147d947)
[[submodule][cloud-provider-azure] Update to ce02abccf](https://github.com/openshift/windows-machine-config-operator/pull/1657/commits/c15eb04db66747dd33223daf6050dd85f990aab8)

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by mtnbikenc** [comment]
`"Process did not finish before 4h0m0s timeout"`
/retest-required

**Comment by aravindhp** [comment]
/override ci/prow/vsphere-e2e-operator 

Given vsphere-e2e-operator [passed]([1672298628674228224](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1657/pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-operator/1672298628674228224)) in a prior run

**Comment by aravindhp** [comment]
Tests are being run again because https://github.com/openshift/windows-machine-config-operator/pull/1664 merged and that has not operator code changes to warrant retesting

/override ci/prow/wicd-unit-vsphere ci/prow/unit  ci/prow/platform-none-vsphere-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/lint ci/prow/images ci/prow/gcp-e2e-operator ci/prow/ci-index-wmco-bundle ci/prow/build ci/prow/azure-e2e-operator ci/prow/azure-e2e-ccm-install ci/prow/aws-e2e-upgrade ci/prow/aws-e2e-operator

**Pull request merged**
