### PR TITLE
[release-4.12] Add goio to linter

### PR DESCRIPTION
**Pull request by aravindhp**
This is a manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1596

/assign aravindhp

### CODE REVIEW

**Comment by aravindhp** [comment]
/hold

For 7.1.0 release

**Review by sebsoto — APPROVED** [review]

**Comment by aravindhp** [comment]
/override ci/prow/vsphere-e2e-operator

Test passed but [failed](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1648/pull-ci-openshift-windows-machine-config-operator-release-4.12-vsphere-e2e-operator/1696194960224686080) in deprovision

**Pull request merged**
