### PR TITLE
Release 4.12 submodule update 12 21

### PR DESCRIPTION
**Pull request by wgahnagl**
[[submodule][ovn-kubernetes] Update to 92058ede9](https://github.com/openshift/windows-machine-config-operator/commit/fee9560da3e59890593b33c3a3e0b4dcce871ba4)
[[submodule][containernetworking-plugins] Update to 1b339719](https://github.com/openshift/windows-machine-config-operator/commit/0014245769b001ae3983c99af508efc40058b728)
[[submodule][windows_exporter] Update to 832186c](https://github.com/openshift/windows-machine-config-operator/commit/c9a841829778b54b8b7ba876f8a36e4284697e54)
[[vendor] Use v1.25.16+a4e782e k8s and OpenShift libraries](https://github.com/openshift/windows-machine-config-operator/commit/5221834b05e3f7ea39baddf79858bcf5cce1a2a8)
[[submodule][cloud-provider-azure] Update to 2193ccfa8](https://github.com/openshift/windows-machine-config-operator/commit/bf1997e7d56a5328d37f582e14000861db2b2306)

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by jrvaldes** [comment]
/test vsphere-e2e-operator

failed creating infrastructure resources

**Comment by alinaryan** [comment]
/close
in favor or #1994

**Pull request closed without merging**
