### PR TITLE
WINC-1314: Use 4.17 Red Hat operator index

### PR DESCRIPTION
**Pull request by sebsoto**
Labels the bundle to be included in the 4.17 Red Hat operator index

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Review by mansikulkarni96 — APPROVED** [review]

**Comment by sebsoto** [comment]
/override ci/prow/aws-e2e-operator ci/prow/azure-e2e-operator ci/prow/azure-e2e-upgrade ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator ci/prow/vsphere-e2e-operator ci/prow/wicd-unit-vsphere

**Pull request merged**
