### PR TITLE
Add sebsoto as an approver

### PR DESCRIPTION
**Pull request by sebsoto**

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/lgtm

**Comment by aravindhp** [comment]
/override ci/prow/azure-e2e-operator
/override ci/prow/aws-e2e-operator-with-custom-vxlan-port
/lgtm cancel

@ravisantoshgudimetla please lgtm

**Review by ravisantoshgudimetla — APPROVED** [review]
/approve

Thank you for all the hardwork @sebsoto

**Pull request merged**
