### PR TITLE
[wmco] Remove apis/ directory and package

### PR DESCRIPTION
**Pull request by sebsoto**
The schema adding logic was already moved into main.go, the extra
schema adding is superflous.
This as a whole is uneeded as we have no CRDs being introduced by the
operator. The directory will be regenerated in the case a CRD is added.

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
Thanks for doing this, @sebsoto 

/approve

**Comment by sebsoto** [comment]
/hold
while network test issues persist

**Pull request merged**
