### PR TITLE
[wmcb] Fix e2e tests that reference "run"

### PR DESCRIPTION
**Pull request by aravindhp**
Replace "run" with "initialize-kubelet" that was introduced in #70.

### CODE REVIEW

**Comment by sebsoto** [comment]
I agree with @ravisantoshgudimetla comment but otherwise
/lgtm

**Comment by aravindhp** [comment]
I have added a new Makefile endpoint called `build-wmcb-e2e-test` that builds a Windows binary that can run the e2e tests. This makes our testing methodology for wmcb consistent across unit and e2e tests.

```
[aravindh@aravindh-dev windows-machine-config-operator]$ make all
CGO_ENABLED=0 GO111MODULE=on GOOS=windows go build -o wmcb.exe  github.com/openshift/windows-machine-config-operator/cmd/bootstrapper
CGO_ENABLED=0 GO111MODULE=on go build -o wni github.com/openshift/windows-machine-config-operator/tools/windows-node-installer
CGO_ENABLED=0 GO111MODULE=on GOOS=windows GOFLAGS=-v go test -c ./pkg/... -o wmcb_unit_test.exe
CGO_ENABLED=0 GO111MODULE=on GOOS=windows GOFLAGS=-v go test -c ./test/e2e... -o wmcb_e2e_test.exe
hack/verify-gofmt.sh
```
@ravisantoshgudimetla @sebsoto  PTAL

**Pull request merged**
