### PR TITLE
[release-4.12] WINC-925: submodule update 02/21

### PR DESCRIPTION
**Pull request by mansikulkarni96**

### CODE REVIEW

**Comment by aravindhp** [comment]
@mansikulkarni96 given we are blocked waiting for the 7.0.1 release. We can wait to merge this after https://github.com/openshift/windows-machine-config-operator/pull/1408 merges and you re-run the command with the version fix.

**Comment by aravindhp** [comment]
/retitle [release-4.12] WINC-925: submodule update 02 10

**Comment by mtnbikenc** [comment]
@mansikulkarni96 Since #1407 has merged, please rebase this PR and update again so we pick up the kube version updates.  Thanks!

**Review by aravindhp — APPROVED** [review]

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by aravindhp** [comment]
[release-4.12] WINC-925: submodule update 02/21

**Pull request merged**
