### PR TITLE
[release-4.12] [test] Capture stderr on oc adm node-logs failures 

### PR DESCRIPTION
**Pull request by alinaryan**
Manual cherry-pick of https://github.com/openshift/windows-machine-config-operator/pull/1464 and https://github.com/openshift/windows-machine-config-operator/pull/1531

### CODE REVIEW

**Review by sebsoto — APPROVED** [review]

**Comment by alinaryan** [comment]
/test azure-e2e-operator

overall cluster install failure

`openshift cluster install failed with cluster creation`

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1534/pull-ci-openshift-windows-machine-config-operator-release-4.12-azure-e2e-operator/1641874871744991232

**Comment by sebsoto** [comment]
/approve cancel
Can cherry-pick https://github.com/openshift/windows-machine-config-operator/pull/1533

**Pull request closed without merging**
