### PR TITLE
WINC-574: [ci] Introduce retries for WMCO deployment

### PR DESCRIPTION
**Pull request by sebsoto**
This commit makes it so the e2e hack script retries multiple times in
case there is an transient issue when deploying the WMCO.

### CODE REVIEW

**Comment by sebsoto** [comment]
Azure passed - retesting
/test azure-e2e-operator

**Comment by aravindhp** [comment]
Azure passed - retesting
/test azure-e2e-operator

**Review by aravindhp — COMMENTED** [review]
@sebsoto please call out what the transient issue is in the commit message. Also add a comment in the code as to why we have these retries.

**Comment by VaishnaviHire** [comment]
Thanks @sebsoto for adding this fix

/lgtm

**Comment by aravindhp** [comment]
/hold
lets do a few retries on `azure-e2e-operator` to see if the problem shows up and the commit fixes it.

**Comment by aravindhp** [comment]
Azure passed without the etcd issue - retesting
/test azure-e2e-operator

**Comment by sebsoto** [comment]
Azure passed without the etcd issue - retesting
/test azure-e2e-operator

**Comment by mansikulkarni96** [comment]
Azure passed without the etcd issue - retesting
/test azure-e2e-operator

**Comment by aravindhp** [comment]
Azure passed without the etcd issue - retesting
/test azure-e2e-operator

**Comment by aravindhp** [comment]
The issue was reproduced [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/272/pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-operator/1357697515993960448/artifacts/azure-e2e-operator/windows-e2e-operator-test/build-log.txt) and the PR fixes it

/approve
/hold cancel

**Comment by aravindhp** [comment]
```
 STEP 45: FROM image-registry.openshift-image-registry.svc:5000/ci-op-423vyhn8/pipeline@sha256:4fdf778432ee50d50675c660e74f71d54503a6c06f3d51af6a601afdb1b8c966
error: build error: error creating build container: Error initializing source docker://image-registry.openshift-image-registry.svc:5000/ci-op-423vyhn8/pipeline@sha256:4fdf778432ee50d50675c660e74f71d54503a6c06f3d51af6a601afdb1b8c966: error pinging docker registry image-registry.openshift-image-registry.svc:5000: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": dial tcp 172.30.110.249:5000: i/o timeout
2021/02/05 23:14:15 No custom metadata found and prow metadata already exists. Not updating the metadata.
2021/02/05 23:14:15 Ran for 11m12s
error: some steps failed:
  * could not run steps: step windows-machine-config-operator-test failed: the build windows-machine-config-operator-test failed after 7m10s with reason DockerBuildFailed: Dockerfile build strategy has failed.
STEP 44: RUN make build
build/build.sh "build/_output" 
building windows-machine-config-operator...
STEP 45: FROM image-registry.openshift-image-registry.svc:...78432ee50d50675c660e74f71d54503a6c06f3d51af6a601afdb1b8c966
error: build error: error creating build container: Error ...ry.svc:5000/v2/": dial tcp 172.30.110.249:5000: i/o timeout
time="2021-02-05T23:14:15Z" level=info msg="Reporting job state 'failed' with reason 'executing_graph:step_failed:building_project_image'" 
```
/test azure-e2e-operator

**Pull request merged**
