### PR TITLE
[release-4.11] WINC-858: Prep for 6.0.1 release

### PR DESCRIPTION
**Pull request by jrvaldes**
This change bumps the patch version in prep for the next release.

Ran `make bundle`

### CODE REVIEW

**Comment by mtnbikenc** [comment]
@jrvaldes This should be `6.0.1`.

**Comment by jrvaldes** [comment]
> @jrvaldes This should be `6.0.1`.

Fixed.

**Comment by mansikulkarni96** [comment]
Thanks for opening these @jrvaldes 
/lgtm

**Review by aravindhp — APPROVED** [review]

**Comment by aravindhp** [comment]
/override azure-e2e-ccm-install 

PR is provider agnostic and we are seeing installer issues with Azure. Red: OCPBUGS-927

**Comment by aravindhp** [comment]
/override azure-e2e-operator

PR is provider agnostic and we are seeing installer issues with Azure. Red: OCPBUGS-927

**Pull request merged**
