### PR TITLE
Add generated MachineSet.yaml to gitignore

### PR DESCRIPTION
**Pull request by jrvaldes**
This commit exclude the MachineSet.yaml file generated by hack/machineset.sh for local development.

### CODE REVIEW

**Review by sebsoto — APPROVED** [review]

**Comment by jrvaldes** [comment]
@sebsoto  can you override the test?

**Review by mansikulkarni96 — COMMENTED** [review]
/lgtm

**Comment by mansikulkarni96** [comment]
/override ci/prow/aws-e2e-operator ci/prow/azure-e2e-operator ci/prow/azure-e2e-upgrade  ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/vsphere-disconnected-e2e-operator ci/prow/vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator ci/prow/wicd-unit-vsphere

**Pull request merged**
