### PR TITLE
[release-4.7] WINC-555:[submodule][wmcb] Update to 06e0030

### PR DESCRIPTION
**Pull request by aravindhp**
Updates the windows-machine-config-bootstrapper submodule to commit https://github.com/openshift/windows-machine-config-bootstrapper/commit/06e0030562ac01bf90c306adf5d3cc53ad960991

Commands run:
```
cd windows-machine-config-bootstrapper
git checkout release-4.7
git pull
```

### CODE REVIEW

**Comment by aravindhp** [comment]
@mansikulkarni96 please don't cherry pick PRs to master. It should always be the other way around. Moreover we should not cherry-pick submodule bumps across branches. They should always track the respective branches.

**Comment by mansikulkarni96** [comment]
> @mansikulkarni96 please don't cherry pick PRs to master. It should always be the other way around. Moreover we should not cherry-pick submodule bumps across branches. They should always track the respective branches.

@aravindhp ack, I will close the cherry-pick PR's and open individual ones.

**Comment by aravindhp** [comment]
/test vsphere-e2e-operator 

Previous failure was with Machine deletion which cannot be attributed to WMCO. Retry.

**Pull request merged**
