### PR TITLE
[release-4.13] submodule update 06 03

### PR DESCRIPTION
**Pull request by saifshaikh48**

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
@saifshaikh48 I would expect https://github.com/openshift/windows-machine-config-operator/pull/2189/commits/d1061f0874f1bd892d5c63e940e8e670d7553587 which contains the 0.25.0 update to be dropped automatically if you rerun the script since the .gitmodule has been pointed to the 3.13 branch.

**Comment by saifshaikh48** [comment]
@mansikulkarni96 Re-ran the script after pointing windows_exporter to 4.13 and pushed up the resulting commits

**Comment by jrvaldes** [comment]
LGTM

**Pull request merged**
