### PR TITLE
Revert "[ci] Run operator deployment on control plane"

### PR DESCRIPTION
**Pull request by LorbusChris**
This reverts commit 3f0c1620477daff4fa5066b03117a6ae1976e4e8.

### CODE REVIEW

**Comment by aravindhp** [comment]
/hold

@openshift/openshift-team-windows-containers please retest this at least 10 times before we merge. Lets see what kind of signal we get.

**Comment by aravindhp** [comment]
@gmarkley-VI we should hold off on retesting this until #101 merges. Please hit that one instead :-)

**Review by aravindhp — APPROVED** [review]
Thanks for doing this, @LorbusChris

**Review by aravindhp — APPROVED** [review]
/approve

**Comment by gmarkley-VI** [comment]
/test aws-e2e-operator-with-custom-vxlan-port
Cluster failed to come up.

**Comment by aravindhp** [comment]
/test aws-e2e-operator
/test aws-e2e-operator-with-custom-vxlan-port

Clusters are not coming up.

**Comment by gmarkley-VI** [comment]
/test aws-e2e-operator
/test aws-e2e-operator-with-custom-vxlan-port

Clusters are not coming up.

**Comment by LorbusChris** [comment]
/test aws-e2e-operator
/test aws-e2e-operator-with-custom-vxlan-port

Clusters are not coming up.

**Comment by gmarkley-VI** [comment]
Is this caused by the branch cut?

**Comment by aravindhp** [comment]
> Is this caused by the branch cut?

I don't think so. At this point master and release-4.6 should not be different enough to cause issues. All the branch cut does is stop automatic fast forwarding.

**Comment by aravindhp** [comment]
It's possible that there is an issue with the 4.7 image promotion that's causing this. Let's figure out a development strategy on Monday.

**Comment by LorbusChris** [comment]
the error seems to consistently be this:
```
level=error msg="Cluster operator network Degraded is True with RolloutHung: DaemonSet \"openshift-ovn-kubernetes/ovnkube-node\" rollout is not making progress - pod ovnkube-node-4sznh is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-node\" rollout is not making progress - pod ovnkube-node-ljcsp is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-node\" rollout is not making progress - pod ovnkube-node-mgw2z is in CrashLoopBackOff State\nDaemonSet \"openshift-ovn-kubernetes/ovnkube-node\" rollout is not making progress - last change 2020-10-04T14:04:04Z"
```
so it's an issue with OVN?

**Comment by aravindhp** [comment]
It needn't be. I suspect an image promotion issue. Seen this happen every time there is a master switch over.

**Comment by LorbusChris** [comment]
From kubelet logs it looks like the cluster-policy-controller is in a crashloop. The pod logs itself show a lot of this:
```
I1005 03:49:45.812339       1 namespace_scc_allocation_controller.go:114] Repairing SCC UID Allocations
E1005 03:49:45.820130       1 namespace_scc_allocation_controller.go:259] rangeallocations.security.internal.openshift.io "scc-uid" is forbidden: User "system:serviceaccount:openshift-infra:namespace-security-allocation-controller" cannot get resource "rangeallocations" in API group "security.internal.openshift.io" at the cluster scope
```

**Comment by aravindhp** [comment]
The real issue turns to be that RCHOS needs to be promoted to 4.7 manually and that process has not been done yet.

**Comment by sdodson** [comment]
Seems like the RHCOS promotion still hasn't happened.

**Comment by aravindhp** [comment]
/test aws-e2e-operator-with-custom-vxlan-port

`aws-e2e-operator` has passed enough number of times.

**Pull request merged**
