### PR TITLE
[wip] [wni] Add enable winrm port e2e test 

### PR DESCRIPTION
**Pull request by leonjia0112**
This is PR depends on #47 . The reason for opening this PR is giving an example of getting the instance credential and decrypt it for @ravisantoshgudimetla and @sebsoto . Don't review yet. Work in Progress.

DO NOT REVIEW FOR NOW!!

### CODE REVIEW

**Comment by leonjia0112** [comment]
Added to tests to the `test-e2e-tools`. First test verify the new instance has winrm port open and the second test verify ansible connection is working by testing a `win_ping` module to the instance.
Ready for an initial review. @aravindhp @ravisantoshgudimetla 
Thanks.

**Comment by leonjia0112** [comment]
Update: This test pass locally, the current challenge is to let ci-operator to run ansible so it is not getting `ansible can not connect to the windows erro`. This could either be done on the ci-operator `openshift/release` repo or this repo. @suhanime is also working on similar challenge. She should be able to give more information.

**Comment by aravindhp** [comment]
Closing this for now until someone else has cycles to pick this up

**Pull request closed without merging**
