### PR TITLE
[release-4.13] WINC-1047: Add support for Windows Server 2022 in AWS

### PR DESCRIPTION
**Pull request by aravindhp**
Update to https://github.com/openshift/ovn-kubernetes/commit/db0dbadc1a409f40345e921e991bd3e22c55490a which will pick up the fix for [OCPBUGS-13170](https://issues.redhat.com/browse/OCPBUGS-13170). The fix will prevent hybrid-overlay from overwriting the non-persistent routes for the metadata endpoint on AWS Windows Server 2022 instances. Once this PR merges, a follow up PR to the release repo will be required to actually start testing Windows Server 2022 on 4.13 AWS clusters.

### CODE REVIEW

**Comment by aravindhp** [comment]
/retitle [release-4.13] WINC-1047: Add support for Windows Server 2022 in AWS

**Comment by mtnbikenc** [comment]
vsphere-e2e-operator took nearly two hours to acquire a lease.  It will probably fail and require another retest.

**Comment by mtnbikenc** [comment]
Seen this error twice, might be something to investigate as mentioned in Slack.
```
    create_test.go:203: 
        	Error Trace:	/go/src/github.com/openshift/windows-machine-config-operator/test/e2e/create_test.go:203
        	Error:      	Received unexpected error:
        	            	timed out waiting for the condition
        	Test:       	TestWMCO/create/Creation/ConfigMap_controller/VM_is_configured_by_ConfigMap_controller
        	Messages:   	Windows node creation failed
```
/retest-required

**Pull request merged**
