### PR TITLE
[hack] Add Azure File CSI Driver Manifests

### PR DESCRIPTION
**Pull request by jfrancoa**
This patch adds the required manifests, in its ideal order, to ensure that Windows workloads can be created with Azure File CSI storage.

### CODE REVIEW

**Comment by jfrancoa** [comment]
```
$ ls
01-example-driver-daemonset.yaml  02-example-namespace.yaml  03-example-sc.yaml  04-example-pvc.yaml  05-example-deployment.yaml

$ oc apply -f 01-example-driver-daemonset.yaml 
daemonset.apps/azure-file-csi-driver-node-windows created

$ oc apply -f 02-example-namespace.yaml 
namespace/windows-storage-example created

$ oc apply -f 03-example-sc.yaml 
storageclass.storage.k8s.io/example-windows-sc created


$ oc apply -f 04-example-pvc.yaml 
persistentvolumeclaim/example-windows-pvc created

$ oc apply -f 05-example-deployment.yaml 
Warning: would violate PodSecurity "restricted:latest": runAsNonRoot != true (pod or container "example-windows-container" must set securityContext.runAsNonRoot=true)
deployment.apps/example-windows-pod created

$ oc get pods -n windows-storage-example
NAME                                  READY   STATUS    RESTARTS   AGE
example-windows-pod-fd576fcdb-cvcdm   1/1     Running   0          2m13s

$ oc get pvc -n windows-storage-example
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS         AGE
example-windows-pvc   Bound    pvc-8bc473af-138e-415e-97fd-17e04d5aaa39   2Gi        RWX            example-windows-sc   5m3s

$ oc get storageclass
NAME                    PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azurefile-csi           file.csi.azure.com   Delete          Immediate              true                   5h2m
example-windows-sc      file.csi.azure.com   Delete          Immediate              false                  5m25s
managed-csi (default)   disk.csi.azure.com   Delete          WaitForFirstConsumer   true                   5h2m

$ oc get ds -n openshift-cluster-csi-drivers 
NAME                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR              AGE
azure-disk-csi-driver-node           6         6         6       6            6           kubernetes.io/os=linux     5h2m
azure-file-csi-driver-node           6         6         6       6            6           kubernetes.io/os=linux     5h2m
azure-file-csi-driver-node-windows   2         2         2       2            2           kubernetes.io/os=windows   5m52s

```

**Review by sebsoto — APPROVED** [review]

**Review by aravindhp — COMMENTED** [review]
/lgtm

Not sure why the previous lgtm did not take affect

**Comment by aravindhp** [comment]
/override ci/prow/aws-e2e-operator ci/prow/azure-e2e-operator ci/prow/ci-index-wmco-bundle ci/prow/gcp-e2e-operator ci/prow/nutanix-e2e-operator ci/prow/platform-none-vsphere-e2e-operator ci/prow/wicd-unit-vsphere 

PR is just a set of example manifests not used in code or e2e tests

**Comment by aravindhp** [comment]
/override ci/prow/vsphere-e2e-operator ci/prow/vsphere-proxy-e2e-operator

**Pull request merged**
