### PR TITLE
Submodule update with k8s 1.30 rebase

### PR DESCRIPTION
**Pull request by sebsoto**
The bulk of this PR was generated with hack/update_submodules.sh.

It also includes minor changes required for compatibility with 1.30 libraries, which were picked up as part of this update.

### CODE REVIEW

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by mansikulkarni96** [comment]
Thanks for working on this @sebsoto 
/approve

**Review by mansikulkarni96 — APPROVED** [review]

**Pull request merged**
