### PR TITLE
[release-4.11][submodule] Update 10/19 

### PR DESCRIPTION
**Pull request by jrvaldes**
[submodule][windows-machine-config-bootstrapper] Update to https://github.com/openshift/windows-machine-config-bootstrapper/commit/965b69ce91e426d38c321593e9fd73403aa91496
  
[submodule][ovn-kubernetes] Update to https://github.com/openshift/ovn-kubernetes/commit/336fb2b5de75b270927ce348ac8446ceeae8931f
  
[submodule][kubelet] Update to https://github.com/openshift/kubernetes/commit/5157800f2a3bc3f81d386ada3e589b8bee25d19c
  
[submodule][cloud-provider-azure] Update to https://github.com/openshift/cloud-provider-azure/commit/6bf2e3359731d80e75ae7c4d73316f6ef49d751a

Ran: 
```
./hack/update_submodules.sh release-4.11

```

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]

**Comment by jrvaldes** [comment]
/test platform-none-vsphere-e2e-operator

Build windows-machine-config-operator-test failed

**Comment by jrvaldes** [comment]
/hold

To investigate SSH [issues](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1285/pull-ci-openshift-windows-machine-config-operator-release-4.11-azure-e2e-operator/1584310676694765568) with Azure CI.

**Pull request merged**
