### PR TITLE
[release-4.9] Bug 2020350: Get and pass Cluster DNS to wmcb.exe

### PR DESCRIPTION
**Pull request by jrvaldes**
This is a manual cherry-pick of #777

### CODE REVIEW

**Comment by aravindhp** [comment]
@jrvaldes why is this a manual cherry-pick? Did we miss PR ordering?

**Comment by saifshaikh48** [comment]
> @jrvaldes why is this a manual cherry-pick? Did we miss PR ordering?

@aravindhp I'd assume vendoring conflicts (though I see the point, there may be new vendoring conflicts once the other backports ahead in the queue merge)

**Comment by jrvaldes** [comment]
/hold

until https://github.com/openshift/windows-machine-config-operator/pull/874 merges

**Comment by jrvaldes** [comment]
/hold cancel

#874 merged

**Comment by selansen** [comment]
Is this still going to be a manual pick or can we use the bot to achieve this?

**Pull request merged**
