### PR TITLE
[deploy] Update operator capability to 'Seamless upgrades'

### PR DESCRIPTION
**Pull request by mansikulkarni96**
This PR updates the operator capability in the WMCO CSV to Seamless upgrades indicating it supports upgrades now.

### CODE REVIEW

**Review by aravindhp — APPROVED** [review]
/approve

**Comment by aravindhp** [comment]
```
error: unable to read image registry.build02.ci.openshift.org/ci-op-dy3m7cxi/stable@sha256:afa5603851ce1f5c4f63a3890694e7ed7802587f84cb85cc1a95d7942e07f177: unknown: unable to pull manifest from registry.svc.ci.openshift.org/ocp/4.8@sha256:afa5603851ce1f5c4f63a3890694e7ed7802587f84cb85cc1a95d7942e07f177: manifest unknown: manifest unknown
68
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-02-07T15:08:07Z"}
```
/hold
Seems like there is an issue since the cutover to 4.8

**Comment by aravindhp** [comment]
/hold cancel

The issue has been resolved.

**Comment by mansikulkarni96** [comment]
The test passed on final run.
/hold cancel

**Pull request merged**
