### PR TITLE
[release-4.15] submodule update 05 22

### PR DESCRIPTION
**Pull request by mansikulkarni96**

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Comment by jrvaldes** [comment]
@mansikulkarni96  submodule update is picking up the latest from windows_exporter and failing due the the slice package not present in the image.

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_windows-machine-config-operator/2181/pull-ci-openshift-windows-machine-config-operator-release-4.12-ci-bundle-wmco-bundle/1793285189921673216#1:build-log.txt%3A853

**Comment by mansikulkarni96** [comment]
slice package is present in go1.21, but we are on go1.20 for relase-4.15/4.14. This raises a question if we should upgrade to windows-exporter latest on versions below release-4.16?

**Comment by jrvaldes** [comment]
> slice package is present in go1.21, but we are on go1.20 for relase-4.15/4.14. This raises a question if we should upgrade to windows-exporter latest on versions below release-4.16?

correct, and we may need to introduce a trunk branch approach in the .gitmodules for `windows_exporter` so that prev branches does not pull from master.  https://github.com/openshift/windows-machine-config-operator/blob/master/.gitmodules#L14

cc @sebsoto

**Pull request closed without merging**
