### PR TITLE
[release-4.9][submodule] update 03/01

### PR DESCRIPTION
**Pull request by wgahnagl**
[submodule][windows_exporter] Update to 7c0474e
[submodule][windows-machine-config-bootstrapper] Update to d833464

### CODE REVIEW

**Comment by wgahnagl** [comment]
/retest-required 

Tests failed with networking errors 

```level=error
level=error msg=Error: Error launching source instance: InvalidNetworkInterface.InUse: Interface: [eni-0e9645b92cc5863d3] in use.
level=error msg=	status code: 400, request id: 5f4fbd47-7a4e-489f-a5ed-442d3b42baf4
level=error
level=error msg=  on ../tmp/openshift-install-cluster-028530919/master/main.tf line 129, in resource "aws_instance" "master":
level=error msg= 129: resource "aws_instance" "master" {
level=error
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change ``` 

```

``` === RUN   TestWMCO/network/East_West_Networking
=== RUN   TestWMCO/network/East_West_Networking/e2e-wm-jzcbr
panic: test timed out after 20m0s ```

**Comment by wgahnagl** [comment]
/retest-required 

```
Error from server (Forbidden): pods "must-gather-" is forbidden: error looking up service account openshift-must-gather-h8vjl/default: serviceaccount "default" not found
{"component":"entrypoint","error":"wrapped process failed: exit status 123","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-03-01T20:41:11Z"}
error: failed to execute wrapped command: exit status 123 ```

**Comment by sebsoto** [comment]
/hold
Azure network tests are failing

**Comment by wgahnagl** [comment]
/retest-required 

ci/prow/azure-e2e-operator failing with a timeout 

``` 2023/03/02 04:12:58 1m0.051833205s time is required to configure 1 nodes
2023/03/02 04:13:58 1m0.051504807s time is required to configure 1 nodes
=== RUN   TestWMCO/network/East_West_Networking
=== RUN   TestWMCO/network/East_West_Networking/e2e-wm-4kzvf
panic: test timed out after 20m0s
goroutine 247 [running]: ```

**Comment by sebsoto** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1443/pull-ci-openshift-windows-machine-config-operator-release-4.9-azure-e2e-operator/1631115516565262336/artifacts/azure-e2e-operator/gather-extra/artifacts/deployments.json
```
            "status": {
                "conditions": [
                    {
                        "lastTransitionTime": "2023-03-02T04:23:59Z",
                        "lastUpdateTime": "2023-03-02T04:23:59Z",
                        "message": "Deployment does not have minimum availability.",
                        "reason": "MinimumReplicasUnavailable",
                        "status": "False",
                        "type": "Available"
                    },
                    {
                        "lastTransitionTime": "2023-03-02T04:34:00Z",
                        "lastUpdateTime": "2023-03-02T04:34:00Z",
                        "message": "ReplicaSet \"win-webserver-e2e-wm-4kzvf-deployment-msp56-79b56fd857\" has timed out progressing.",
                        "reason": "ProgressDeadlineExceeded",
                        "status": "False",
                        "type": "Progressing"
                    }
                ],
```

**Comment by aravindhp** [comment]
/hold 
@wgahnagl how can the submodule update go through which is removing 20H2 support without https://github.com/openshift/windows-machine-config-operator/pull/1413 merging?

**Comment by aravindhp** [comment]
/retitle [release-4.9][submodule] update 03/01

@wgahnagl lets avoid repeating words in headers in the future

**Comment by wgahnagl** [comment]
/retest-required

#1413 has merged, tests should pass now :+1:

**Comment by wgahnagl** [comment]
/retest-required 

another flake since tests were passing before removing the hold 

```make: *** [Makefile:180: run-ci-e2e-test] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-03-03T18:56:24Z"}
error: failed to execute wrapped command: exit status 2 ```

**Comment by aravindhp** [comment]
@wgahnagl please provide links to job that flaked. It also looks the snippet you have added is not the real issue.

**Comment by wgahnagl** [comment]
/retest-required 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1443/pull-ci-openshift-windows-machine-config-operator-release-4.9-aws-e2e-upgrade/1631704977648914432 

```level=error
level=error msg=Error: Error launching source instance: InvalidNetworkInterface.InUse: Interface: [eni-00fcb8927b10376f6] in use.
level=error msg=	status code: 400, request id: 9ff157b6-de1f-4853-9cae-6b2ca40ace64
level=error
level=error msg=  on ../tmp/openshift-install-cluster-166832766/master/main.tf line 129, in resource "aws_instance" "master":
level=error msg= 129: resource "aws_instance" "master" {
level=error
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change ```

**Pull request merged**
