### PR TITLE
Prep for 5.0.0 release

### PR DESCRIPTION
**Pull request by sebsoto**
Ran `make bundle` after changing the Makefile and `config/` files.

### CODE REVIEW

**Review by jrvaldes — APPROVED** [review]
/lgtm

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Review by aravindhp — APPROVED** [review]
Thanks for doing this, @sebsoto 

/approve

**Comment by jrvaldes** [comment]
HOLD
Needs rebase  https://github.com/openshift/windows-machine-config-operator/pull/781

**Comment by aravindhp** [comment]
@jrvaldes why does this need a rebase now that #781 has merged?

**Comment by jrvaldes** [comment]
> @jrvaldes why does this need a rebase now that #781 has merged?

It does not, got confused.

**Pull request merged**
